# Modelo de NLP para Reconhecimento de Entidades em Documentos Jurídicos

A solução que criei é capaz de identificar automaticamente informações críticas, como nomes das partes envolvidas, datas relevantes e dispositivos legais citados, em contratos, petições e jurisprudências. O projeto simula um cenário real, no qual uma grande empresa de advocacia precisava de uma forma eficiente de extrair dados importantes de um volume significativo de textos legais. Com essa solução, demonstrei como a IA pode ser aplicada para agilizar a análise de documentos, reduzir erros manuais e melhorar a gestão de processos no setor jurídico.

Além do desenvolvimento do algoritmo de machine learning, foi criada uma aplicação interativa para visualizar os resultados do modelo de reconhecimento de entidades nomeadas. Essa aplicação permite que os usuários insiram textos ou carreguem arquivos para análise, proporcionando uma interface intuitiva para explorar as entidades extraídas pelo modelo.

# Leitura dos textos

In [ ]:
import zipfile

In [ ]:
with zipfile.ZipFile('/content/texts.zip', 'r') as zip:
    print(zip.namelist())

In [ ]:
with zipfile.ZipFile('/content/texts.zip', 'r') as zip:
    print(*zip.namelist(), sep = '\n')

ADI2TJDFT.txt
adi3767.txt
Ag10000170733596001.txt
Ag10105170208398001.txt
AgAIRR11889820145030011.txt
AgCr10582160008758001.txt
AgRgSTJ1.txt
AgRgSTJ2.txt
AgRgTSE1.txt
AgRgTSE3.txt
AIAgRAgI6193ARAGUARIMG.txt
airr801422012.txt
AIRR3999520145020086.txt
AIRR15708820115050222.txt
AP00000794920137060006.txt
AP00001415620157010201.txt
AP00001441420167030203.txt
AP771420167080008PA.txt
CP32320177080008PA.txt
DespSEPLAGDF.txt
ED1STM.txt
ED1TJAC.txt
EDAgRgTSE2.txt
EDEDARR208420135040232.txt
EDRR1TST.txt
EEDRR9715120105020002.txt
ERR731004520105130003.txt
HC110260SP.txt
HC151914AgRES.txt
HC340624SP.txt
HC418951PR.txt
HC70000845920187000000.txt
lei11340.txt
Lei11788.txt
LoaDF2018.txt
Pet128TSE5.txt
Port77DF.txt
Rcl3495STJ.txt
REE5908TSE4.txt
REsp1583083RS.txt
RR474820145230056.txt
RR942006420095040028.txt
RR2574407120025020372.txt
TCU4687.txt
TSTRR16037920105200001.txt
AC1TCU.txt
AC1TJAC.txt
AC1TJMG.txt
AC2.txt
ACORDAOTCU25052016.txt

In [ ]:
with zipfile.ZipFile('/content/texts.zip', 'r') as zip:
    with zip.open('ADI2TJDFT.txt') as arquivo:
        texto = arquivo.read().decode('utf-8')

In [ ]:
# print(texto)

**Reconhecendo as entidades no texto**

> Para fazer o reconhecimento das entidades nos textos, usarei a biblioteca `SpaCy`, na qual me permite utilizar modelos já treinados e personalizá-los para atender ao problema específico.

In [ ]:
# !pip install -U spacy

In [ ]:
# !python -m spacy download pt_core_news_sm

In [ ]:
import spacy
import pt_core_news_sm

modelo_ner = pt_core_news_sm.load()

In [ ]:
doc = modelo_ner(texto)

for entidade in doc.ents:
    print(f'{entidade.text} -> {entidade.label_}')

Órgão -> LOC
Conselho Especial
Classe -> ORG
DISTRITO FEDERAL E TERRITÓRIOS
Requerido(s -> LOC
DA CÂMARA -> ORG
DISTRITO FEDERAL E OUTRO(S)
Relator -> LOC
LEIS DISTRITAIS -> MISC
COMPLEMENTAR DISTRITAL -> MISC
FORMAL -> ORG
LEI ORGÂNICA -> MISC
DISTRITO FEDERAL -> LOC
ÁREA PÚBLICA -> LOC
DO GOVERNADOR -> MISC
DISTRITO FEDERAL -> LOC
VÍCIO FORMAL -> ORG
Decreto n.º 10.829/87 -> MISC
Portaria n.º 314/92 -> ORG
Instituto Brasileiro do Patrimônio Cultural  IBPC -> LOC
Instituto do Patrimônio Histórico e Artístico Nacional  IPHAN -> LOC
Governador do Distrito Federal -> LOC
Distrito Federal -> LOC
ACÓRDÃO -> ORG
Acordam os Desembargadores do Conselho Especial do Tribunal de Justiça do Distrito Federal -> MISC
Territórios LÉCIO RESENDE  Relator -> ORG
JOÃO MAIORISI -> PER
Vogal -> ORG
VIEIRA  Vogal -> LOC
SÉRGIO BITTENCOURT  Vogal -> ORG
LECIR MANOEL DA LUZ -> ORG
Vogal -> LOC
CARMELITA BRASIL -> ORG
Vogal -> LOC
WALDIR LEÔNCIO -> PER
J.J. COSTA CARVALHO -> PER
Vogal -> LOC
HUMBERTO -> LOC
Vogal -> LOC
NÍDIA CORRÊA LIMA  Vogal -> ORG
CRUZ -> LOC
Vogal -> LOC
ROBERBAL CASEMIRO BELINATI -> MISC
Vogal -> LOC
SILVÂNIO -> ORG
Vogal -> ORG
OTÁVIO AUGUSTO  Vogal -> LOC
Desembargador OTÁVIO AUGUSTO -> MISC
JULGOU-SE PROCEDENTE -> PER
MAIORIA -> MISC
Brasília -> LOC
DF -> LOC
Des -> MISC
LÉCIO -> MISC
DISTRITO FEDERAL E TERRITÓRIOS propõe Ação Direta de Inconstitucionalidade -> LOC
Leis distritais n.º 747 -> MISC
Lei Complementar -> MISC
Região Administrativa do Paranoá  RA VII -> LOC
XI -> LOC
XXI -> LOC
Lei Orgânica do Distrito Federal  LODF -> MISC
Narra -> LOC
Chefe do Poder Executivo -> MISC
Poder Legislativo -> PER
Requer -> PER
Leis distritais n.º 747/1994 -> MISC
Lei Complementar distrital n.º 380/2001 -> MISC
fls -> MISC
Presidente da Câmara Legislativa do Distrito Federal -> MISC
fls -> MISC
Governador do Distrito Federal -> LOC
Sustenta -> LOC
Câmara distrital -> LOC
LODF -> ORG
Governador do Distrito Federal -> LOC
fls -> MISC
Procurador-Geral -> LOC
Distrito Federal -> LOC
fls -> MISC
Parecer Ministerial de fls -> MISC
Relatório -> LOC
O Senhor Desembargador LÉCIO RESENDE   -> MISC
DISTRITO FEDERAL E TERRITÓRIOS propõe Ação Direta de Inconstitucionalidade -> LOC
Leis distritais n.º 747 -> MISC
Lei Complementar -> MISC
Região Administrativa do Paranoá  RA VII -> LOC
Chefe do Poder Executivo -> MISC
Poder Legislativo -> PER
XI -> LOC
XXI -> LOC
Lei Orgânica do Distrito Federal  LODF -> MISC
Requer -> PER
Lei Orgânica do Distrito Federal -> MISC
Ação Direta -> PER
Carta Magna -> LOC
Ação Direta de Inconstitucionalidade -> MISC
I -> MISC
Carta Magna -> LOC
Constituição Federal -> ORG
Estados -> LOC
Constituição -> ORG
Estados -> LOC
Constituição -> ORG
Distrito Federal -> LOC
Lei Orgânica -> MISC
Distrito Federal -> LOC
Federação brasileira -> LOC
Ministro CELSO DE MELLO -> PER
ADI -> ORG
A Lei Orgânica do Distrito Federal -> MISC
Federação brasileira -> LOC
Distrito Federal -> LOC
A Lei Orgânica -> MISC
Constituições -> LOC
DJU de 13 -> MISC
Lei Orgânica do Distrito Federal -> MISC
Estados-membros -> MISC
Supremo Tribunal Federal -> LOC
ADI -> ORG
DF -> LOC
Tribunal de Justiça do Distrito Federal -> ORG
Territórios -> LOC
Lei Orgânica do Distrito Federal -> MISC
Ação Direta de Inconstitucionalidade -> MISC
Ação Declaratória de Constitucionalidade -> ORG
Tribunal de Justiça do Distrito Federal -> ORG
Territórios -> LOC
Carta Magna -> ORG
III -> LOC
Regimento Interno -> MISC
Tribunal de Justiça -> ORG
Procurador-Geral de Justiça do Distrito Federal e Territórios -> LOC
Ação Direta de Inconstitucionalidade -> MISC
Admito -> MISC
Excelentíssima Senhora PROCURADORA-GERAL DE JUSTIÇA DO -> MISC
DISTRITO FEDERAL E TERRITÓRIOS -> LOC
Leis distritais -> MISC
Nº 747 -> MISC
Autor do Projeto -> MISC
Deputado Salviano Guimarães -> PER
Promulgação -> MISC
Sr. -> LOC
Distrito Federal -> LOC
Projeto de Lei -> MISC
Autoriza o Poder Executivo -> PER
Zona de Expansão Urbana do Paranoá  7 ZEU -> LOC
Câmara Legislativa do Distrito Federal -> LOC
Lei Orgânica do Distrito Federal -> MISC
Lei nº 747 -> MISC
Art. 1º Fica o Poder Executivo -> MISC
Zona de Expansão Urbana 1 -> LOC
Paranoá  7 ZEU -> MISC
Lei nº 353 -> MISC
Vila Paranoá -> LOC
Programa de Assentamento da População de Baixa Renda -> MISC
O Poder Executivo -> MISC
Decreto nº 11.208 -> MISC
Associação de Moradores do Paranoá -> ORG
Zona de Expansão Urbana 1 -> LOC
Paranoá  7 ZEU -> MISC
Área de Proteção Ambiental -> ORG
Lago Paranoá -> LOC
Poder Executivo -> PER
Lei -> MISC
Art. 5º -> MISC
Nº -> MISC
Autoria do Projeto -> MISC
Deputado José Edmar -> PER
Destina -> PER
Complexo Vivencial -> LOC
Esportivo do Paranoá -> LOC
Região Administrativa do Paranoá  RA VII -> LOC
Câmara Legislativa do Distrito Federal -> LOC
Governador do Distrito Federal -> LOC
Lei Orgânica do Distrito Federal -> MISC
Presidente da Câmara Legislativa do Distrito Federal -> LOC
Lei:
Art. 1º -> MISC
Complexo Vivencial -> LOC
Esportivo do Paranoá -> LOC
Região Administrativa do Paranoá  RA VII -> LOC
Quadras 3 -> MISC
DF -> LOC
DF -> LOC
IV -> MISC
Região Administrativa do Paranoá -> LOC
O Complexo Vivencial -> MISC
Esportivo do Paranoá -> LOC
Local do Paranoá -> LOC
Plano Diretor de Ordenamento Territorial do Distrito Federal  PDOT -> MISC
Art. 4º -> MISC
Nº 380 -> MISC
Autoria do Projeto -> MISC
Deputado César Lacerda -> PER
Região Administrativa do Paranoá  RA VII -> LOC
Presidente da Câmara Legislativa do Distrito Federal -> MISC
Lei Orgânica do Distrito Federal -> MISC
Lei Complementar -> PER
Projeto -> MISC
Governador do Distrito Federal -> LOC
Câmara Legislativa do Distrito Federal -> LOC
Região Administrativa do Paranoá  RA VII -> LOC
DF-001 -> LOC
Estrada Parque Contorno  EPCT -> LOC
Região Administrativa do Paranoá  RA VII -> LOC
Rodovia DF-001 -> LOC
EPCT -> MISC
Anexo II da Lei Complementar -> LOC
Art. 2º Fica -> MISC
Norma de Edificação -> MISC
Uso -> LOC
Gabarito  NGB -> LOC
Lei Complementar -> PER
Região Administrativa do Paranoá  RA VII -> LOC
O Poder Executivo -> MISC
Lei Complementar -> PER
Art. 5º -> MISC
Lei Complementar -> PER
Lei Orgânica do Distrito Federal -> MISC
Distrito Federal -> LOC
XI -> LOC
Brasília -> LOC
Livro do Tombo Histórico -> MISC
Decreto n.º 10.829, de 2 de outubro de 1987 -> MISC
Portaria n.º 314 -> ORG
Instituto Brasileiro do Patrimônio Cultural -> LOC
Instituto do Patrimônio Histórico e Artístico Nacional -> LOC
Inciso -> PER
Emenda a Lei Orgânica n.º 12 -> MISC
 DODF -> MISC
Poder Executivo -> MISC
Distrito Federal -> LOC
Câmara Legislativa -> LOC
Governador do Distrito Federal -> LOC
Lei Orgânica -> MISC
XXI -> LOC
Poder Executivo conduzir -> MISC
Distrito Federal -> LOC
grifo nosso -> MISC
Deputados Distritais -> PER
fls -> MISC
Poder Legislativo -> PER
Distrito Federal -> LOC
Chefe do Poder Executivo -> MISC
Corte -> LOC
Governador do Distrito Federal -> LOC
Distrito Federal -> LOC
DIRETA DE INCONSTITUCIONALIDADE -> MISC
AUTORIA PARLAMENTAR -> LOC
COLIDÊNCIA -> ORG
A LEI ORGÂNICA -> MISC
DISTRITO FEDERAL -> LOC
RESERVA DE INICIATIVA -> ORG
VÍCIO -> ORG
FORMAL DE INCONSTITUCIONALIDADE -> MISC
DO GOVERNADOR -> MISC
DISTRITO FEDERAL PARA A PROPOSITURA DE LEIS -> LOC
ÂMBITO -> MISC
Tribunal de Justiça -> ORG
Poder Legislativo -> PER
Distrito Federal -> LOC
Governador do Distrito Federal -> LOC
XI -> LOC
inciso VI -> PER
Lei Orgânica do Distrito Federal -> MISC
Lei Complementar -> PER
Câmara Legislativa do Distrito Federal -> LOC
Lei Complementar Distrital -> MISC
ADI 2010002007992-9 -> MISC
Conselho Especial -> ORG
Relator Desembargador NATANAEL CAETANO -> MISC
DJ-e de 17/11/2010 -> MISC
AÇÃO DIRETA DE INCONSTITUCIONALIDADE -> MISC
LEIS COMPLEMENTARES DISTRITAIS -> MISC
569/02 -> LOC
USO -> ORG
OCUPAÇÃO -> MISC
DEPUTADOS DISTRITAIS -> MISC
FORMAL -> ORG
INAPLICABILIDADE -> LOC
Distrito Federal -> LOC
Governador -> LOC
Lei Orgânica do Distrito Federal -> MISC
Lei nº 9.868/99 -> MISC
ADI 2010002002050-8 -> MISC
Conselho Especial -> ORG
DJ-e de 17/11/2010 -> MISC
ADMINISTRATIVO -> ORG
DIRETA DE INCONSTITUCIONALIDADE -> MISC
COMPLEMENTAR DISTRITAL -> MISC
Nº 788 -> MISC
DESAFETAÇÃO DE ÁREAS -> MISC
RA IV -> MISC
FORMAL -> ORG
EMENDA PARLAMENTAR -> PER
OFENSA -> ORG
À LEI ORGÂNICA -> MISC
DISTRITO FEDERAL E AOS -> LOC
ADMINISTRATIVOS -> ORG
Lei Complementar -> LOC
Brazlândia-DF  Região Administrativa IV -> LOC
Distrito Federal -> LOC
Chefe do Poder Executivo -> MISC
Corte -> LOC
ADI 2009002013564-6 -> MISC
Conselho Especial -> ORG
Relator Desembargador CRUZ -> PER
DJ-e -> MISC
Distrito Federal -> LOC
Decreto n.º 10.829/1987 -> MISC
Portaria n.º 314/1992 -> ORG
Instituto Brasileiro do Patrimônio Histórico e Artístico Nacional  IPHAN -> LOC
Governador -> LOC
Distrito Federal -> LOC
Câmara Legislativa -> LOC
Vejamos -> MISC
XI -> LOC
Lei Orgânica do Distrito Federal -> MISC
Distrito Federal -> LOC
XI -> LOC
Brasília -> LOC
Livro do Tombo Histórico -> MISC
Decreto -> PER
Portaria n 314 -> ORG
Instituto Brasileiro do Patrimônio Cultural  IBPC -> LOC
Instituto do patrimônio Histórico e Artístico Nacional  IPHAN -> LOC
Decreto -> MISC
Portaria n.º 314/1992 -> ORG
Governador do Distrito Federal -> LOC
Distrito Federal -> LOC
Governador do Distrito Federal -> LOC
Distrito Federal -> LOC
Decreto n.º 10.829/87 -> MISC
Lei Orgânica do Distrito Federal -> MISC
Emenda n.º 12/96 -> MISC
VI -> LOC
LODF -> LOC
Governador do Distrito Federal -> LOC
Distrito Federal -> LOC
Decreto n.º 10.829/87 -> MISC
Portaria n.º 314/92 -> ORG
IPHAN -> ORG
LODF -> ORG
Distrito Federal -> LOC
JULGO -> LOC
Leis distritais n.º 747 -> MISC
Lei Complementar -> MISC
O Senhor Desembargador JOÃO MARIOSI -> MISC
Vogal
Senhor Presidente -> PER
Constituição de 1988 -> ORG
Distrito Federal -> LOC
Ministro Celso de Mello -> PER
S. -> PER
Tribunal -> LOC
Judiciário -> MISC
Constituição -> ORG
Constituição -> ORG
“ -> MISC
Tribunal -> LOC
Câmara Legislativa -> LOC
Governador do Distrito Federal -> LOC
Supremo -> LOC
Tribunal? -> ORG
Evidentemente -> MISC
Lei Orgânica do Distrito Federal -> MISC
Constituições Estaduais -> LOC
Constituições Estaduais -> LOC
Estados -> LOC
Federação -> LOC
Distrito Federal -> LOC
Judiciário -> PER
Ministério Público -> ORG
Ministério Público -> ORG
Distrito Federal -> LOC
Tribunal de Contas -> ORG
Digo -> LOC
Vencido -> MISC
O Senhor Desembargador ROMÃO -> MISC
Desembargador João Mariosi -> PER
Relator -> MISC
O Senhor Desembargador DÁCIO VIEIRA  Vogal
 -> MISC
Ação Direta de Inconstitucionalidade -> MISC
Procuradora-Geral de Justiça do Distrito Federal e Territórios -> ORG
Leis Distritais -> MISC
Lei Complementar -> PER
Região Administrativa do Paranoá  RA VII -> LOC
XI -> LOC
XXI -> LOC
Lei Orgânica do Distrito Federal -> MISC
Sustenta -> PER
“ -> MISC
“ -> MISC
Deputados Distritais -> PER
Governador do Distrito Federal -> LOC
Lei Orgânica do Distrito Federal -> MISC
Órgão Especial -> LOC
Distrito Federal -> LOC
Governador do Distrito Federal -> LOC
”(Conselho Especial -> MISC
ADI -> ORG
Rel -> PER
Des -> PER
Romão C. Oliveira -> PER
Reg -> PER
Ac -> MISC
DIRETA DE INCONSTITUCIONALIDADE -> MISC
LEIS COMPLEMENTARES DISTRITAIS -> MISC
Nº 660 -> MISC
CEILÂNDIA -> ORG
BRASÍLIA -> MISC
OCUPAÇÃO -> ORG
DISTRITO FEDERAL -> LOC
ALEGAÇÃO DE INCONSTITUCIONALIDADE -> MISC
À LEI ORGÂNICA -> MISC
DISTRITO FEDERAL -> LOC
PROCEDÊNCIA -> ORG
Procedência -> PER
Lei Orgânica do Distrito Federal -> MISC
Decreto nº 10.829/1987 -> MISC
XI -> LOC
Lei Orgânica do Distrito Federal -> MISC
Chefe do Poder Executivo -> MISC
Relator MARIO MACHADO -> MISC
Conselho Especial -> ORG
DJ -> ORG
AÇÃO DIRETA DE INCONSTITUCIONALIDADE -> MISC
Nº -> MISC
FORMAL -> ORG
DO GOVERNADOR -> MISC
DISTRITO FEDERAL -> LOC
SOBRE OCUPAÇÃO -> ORG
SOLO -> MISC
Excelentíssimo -> LOC
Governador do Distrito Federal -> LOC
Distrito Federal -> LOC
Conselho Especial -> ORG
ADI -> ORG
Rel -> ORG
Des -> PER
Lécio Resende -> PER
Reg -> PER
Ac -> MISC
AÇÃO DIRETA DE INCONSTITUCIONALIDADE -> MISC
Nº -> MISC
PRELIMINAR DE INÉPCIA -> MISC
INICIAL REJEITADA -> MISC
MÉRITO: ADMINISTRAÇÃO DE ÁREAS PÚBLICAS -> MISC
SOBRE OCUPAÇÃO -> ORG
SOLO -> ORG
VÍCIO -> MISC
DISTRITO FEDERAL -> LOC
Relator DÁCIO VIEIRA -> PER
Conselho Especial -> ORG
DJ -> ORG
Destarte -> LOC
Leis -> LOC
Governador -> LOC
Feitas -> PER
Leis -> PER
O Senhor Desembargador SÉRGIO BITTENCOURT  Vogal
Senhor Presidente -> MISC
Desembargador João Mariosi -> PER
Conselho -> LOC
Ação Direta de Inconstitucionalidade -> MISC
Governador do Distrito Federal -> LOC
Leis Distritais -> MISC
Lei Complementar Distrital -> MISC
Deputados Distritais -> PER
Aduz -> LOC
XI -> LOC
XXI -> LOC
Lei Orgânica do Distrito Federal -> MISC
Leis Distritais -> PER
Presidente da Câmara Legislativa -> MISC
fls -> MISC
Governador do Distrito Federal -> LOC
Procurador-Geral -> LOC
Distrito Federal -> LOC
fls -> MISC
Procuradoria de Justiça -> MISC
fls -> MISC
Leis impugnadas -> MISC
Deputados Distritais -> PER
Governador do Distrito Federal -> LOC
Presidente da Câmara Legislativa -> MISC
Diplomas -> PER
Leis Distritais -> PER
Nº 747 -> MISC
Autoria do Projeto -> MISC
Deputado Salviano Guimarães -> PER
Promulgação -> MISC
Sr. -> LOC
Distrito Federal -> LOC
Projeto de Lei -> MISC
Autoriza o Poder Executivo -> PER
Zona de Expansão Urbana do Paranoá  7 ZEU -> LOC
Câmara Legislativa do Distrito Federal -> LOC
Lei Orgânica do Distrito Federal -> MISC
Lei nº 747 -> MISC
Art. 1º Fica o Poder Executivo -> MISC
Zona de Expansão Urbana 1 -> LOC
Paranoá  7 ZEU -> MISC
Lei nº 353 -> MISC
Vila Paranoá -> LOC
Programa de Assentamento da População de Baixa Renda -> MISC
O Poder Executivo -> MISC
Decreto nº 11.208 -> MISC
Associação de Moradores do Paranoá -> ORG
Zona de Expansão Urbana 1 -> LOC
Paranoá  7 ZEU -> MISC
Área de Proteção Ambiental -> ORG
Lago Paranoá -> LOC
Poder Executivo -> PER
Lei -> MISC
Art. 5º -> MISC
grifo nosso -> MISC
Nº -> MISC
Autoria do Projeto -> MISC
Deputado José Edmar -> PER
Destina -> PER
Complexo Vivencial -> LOC
Esportivo do Paranoá -> LOC
Região Administrativa do Paranoá  RA VII -> LOC
Câmara Legislativa do Distrito Federal -> LOC
Governador do Distrito Federal -> LOC
Lei Orgânica do Distrito Federal -> MISC
Presidente da Câmara Legislativa do Distrito Federal -> LOC
Lei:
Art. 1º -> MISC
Complexo Vivencial -> LOC
Esportivo do Paranoá -> LOC
Região Administrativa do Paranoá  RA VII -> LOC
Quadras 3 -> MISC
DF -> LOC
DF -> LOC
IV -> MISC
Região Administrativa do Paranoá -> LOC
O Complexo Vivencial -> MISC
Esportivo do Paranoá -> LOC
Local do Paranoá -> LOC
Plano Diretor de Ordenamento Territorial do Distrito Federal  PDOT -> MISC
Art. 4º -> MISC
Nº 380 -> MISC
Autoria do Projeto -> MISC
Deputado César Lacerda -> PER
Região Administrativa do Paranoá  RA VII -> LOC
Presidente da Câmara Legislativa do Distrito Federal -> MISC
Lei Orgânica do Distrito Federal -> MISC
Lei Complementar -> PER
Projeto -> MISC
Governador do Distrito Federal -> LOC
Câmara Legislativa do Distrito Federal -> LOC
Região Administrativa do Paranoá  RA VII -> LOC
DF-001 -> LOC
Estrada Parque Contorno  EPCT -> LOC
Região Administrativa do Paranoá  RA VII -> LOC
Rodovia DF-001 -> LOC
EPCT -> LOC
Anexo II da Lei Complementar -> LOC
Art. 2º Fica -> MISC
Norma de Edificação -> MISC
Uso -> LOC
Gabarito  NGB -> LOC
Lei Complementar -> PER
Região Administrativa do Paranoá  RA VII -> LOC
O Poder Executivo -> MISC
Lei Complementar -> PER
Art. 5º -> MISC
Lei Complementar -> PER
grifo nosso -> MISC
Governador do Distrito Federal -> LOC
XI -> LOC
XXI -> LOC
Lei Orgânica do Distrito Federal -> MISC
Distrito Federal -> LOC
Omissis -> MISC
XI -> LOC
Brasília -> LOC
Livro do Tombo Histórico -> MISC
Decreto -> PER
Portaria -> ORG
Instituto Brasileiro do Patrimônio Cultural  IBPC -> LOC
Instituto do Patrimônio Histórico e Artístico Nacional  IPHAN -> LOC
Poder Executivo -> MISC
Distrito Federal -> LOC
Câmara Legislativa -> LOC
Governador do Distrito Federal -> LOC
Omissis -> MISC
Lei Orgânica -> MISC
Poder Executivo conduzir -> MISC
Distrito Federal -> LOC
Decreto nº 10.829/1987 -> MISC
Portaria nº 314/1992 -> ORG
Instituto Brasileiro do Patrimônio Histórico e Artístico Nacional  IPHAN -> LOC
Governador do Distrito Federal -> LOC
Distrito Federal -> LOC
Governador do Distrito Federal -> LOC
Distrito Federal -> LOC
Normas -> LOC
Câmara Legislativa -> LOC
Governador do Distrito Federal -> LOC
Eg -> MISC
Corte -> LOC
DIRETA DE INCONSTITUCIONALIDADE -> MISC
Nº 1.250 -> MISC
NOVEMBRO -> MISC
Nº 1.319 -> MISC
Nº 2.540 -> MISC
NORMATIVOS LOCAIS -> MISC
TRIBUNAL DE JUSTIÇA -> ORG
DISTRITO FEDERAL E TERRITÓRIOS PARA PROCESSAR -> LOC
OCUPAÇÃO -> ORG
SOLO -> ORG
PARLAMENTARES  INCONSTITUCIONALIDADE -> MISC
COMPETÊNCIA -> ORG
DO CHEFE -> MISC
O Conselho Especial do Tribunal de Justiça do Distrito Federal e Territórios -> MISC
Distrito Federal -> LOC
Lei Orgânica -> MISC
Distrito Federal -> LOC
Governador do Distrito Federal -> LOC
Rel -> PER
Des -> PER
João Mariosi -> PER
Conselho Especial -> ORG
DJ-e de 10.02.2010 -> MISC
COMPLEMENTAR DISTRITAL N. -> MISC
CONSTRUÇÃO -> ORG
QUADRA 1 -> MISC
SETOR -> ORG
GRÁFICAS -> LOC
REGIÃO ADMINISTRATIVA -> LOC
VÍCIO FORMAL -> ORG
VÍCIO -> ORG
LEI ORGÂNICA -> MISC
FEDEAL -> ORG
A Lei Orgânica do Distrito Federal -> MISC
XI -> LOC
Decreto n. 10.829/87 -> MISC
Governador do Distrito Federal -> LOC
Distrito Federal -> LOC
Lei Orgânica -> MISC
Governador do Distrito Federal -> LOC
VI -> LOC
Lei Orgânica -> MISC
Decreto -> MISC
Governador -> LOC
Distrito Federal -> LOC
Inexiste -> LOC
Lei Orgânica do Distrito Federal -> LOC
Distrito Federal -> LOC
LODF
Julgado -> LOC
ADI -> ORG
Rel -> ORG
Des -> PER
J. J. Costa Carvalho -> PER
Conselho Especial -> ORG
DJ-e -> MISC
AÇÃO DIRETA DE INCONSTITUCIONALIDADE -> MISC
ÁREA PÚBLICA -> LOC
VÍCIO DE INICIATIVA -> ORG
FORMAL -> ORG
PROCEDÊNCIA -> ORG
EFEITOS EX TUNC -> MISC
Governador do Distrito Federal -> LOC
Distrito Federal -> LOC
Lei n.º 464/1994 -> MISC
Região Administrativa do Cruzeiro -> LOC
Relª. Desa -> PER
Brasil -> LOC
Conselho Especial -> ORG
DJ-e de 08.01.2010 -> MISC
Leis Distritais -> MISC
Lei Complementar Distrital -> MISC
O Senhor Desembargador LECIR MANOEL DA LUZ -> MISC
Vogal -> LOC
Desembargador Romão C. Oliveira -> PER
Desembargador -> PER
Relator -> MISC
A Senhora Desembargadora CARMELITA BRASIL -> MISC
Vogal
Acompanho -> PER
Relator -> MISC
O Senhor Desembargador WALDIR LEÔNCIO JÚNIOR  Vogal
 -> MISC
Relator -> MISC
O Senhor Desembargador J. J. COSTA CARVALHO -> MISC
Vogal
Senhor Presidente -> PER
Relator -> MISC
Desembargador João Mariosi -> PER
O Senhor Desembargador HUMBERTO ADJUTO ULHÔA -> MISC
Relator -> MISC
A Senhora Desembargadora NÍDIA -> MISC
Desembargador João Mariosi -> PER
Relator -> MISC
O Senhor Desembargador CRUZ MACEDO -> MISC
Vogal
Acompanho -> PER
Relator -> MISC
vênia -> LOC
A Senhora Desembargadora ANA -> MISC
Vogal -> LOC
Relator -> MISC
O Senhor Desembargador ROBERVAL -> MISC
BELINATI -> MISC
Vogal
Acompanho -> PER
Relator -> MISC
vênia -> LOC
O Senhor Desembargador SILVÂNIO -> MISC
Vogal -> ORG
Relator -> MISC
O Senhor Desembargador OTÁVIO AUGUSTO  Presidente -> MISC
Vogal
 -> LOC
Procuradora-Geral de Justiça do Distrito Federal e Territórios -> ORG
Leis Distritais -> MISC
Lei Complementar -> PER
XI -> LOC
XXI -> LOC
Lei Orgânica -> MISC
DF -> LOC
Lei Orgânica -> MISC
XI -> LOC
inciso VI -> PER
XXI -> LOC
Chefe do Poder Executivo -> MISC
Entende -> PER
DF -> LOC
Requer -> MISC
Deputados Distritais -> PER
Poder Legislativo -> PER
Distrito Federal -> LOC
Governador do Distrito Federal -> LOC
inciso VI -> PER
Lei Orgânica do Distrito Federal -> MISC
Poder Executivo -> MISC
Distrito Federal -> LOC
Câmara Legislativa -> LOC
Governador do Distrito Federal -> LOC
Lei Orgânica -> MISC
Poder Executivo conduzir -> MISC
Distrito Federal -> LOC
g.n. -> LOC
DF -> LOC
Distrito Federal -> LOC
Poder Executivo -> MISC
Decreto n. 10.829/87 -> MISC
XI -> LOC
LODF -> ORG
Governador do Distrito Federal -> LOC
Distrito Federal -> LOC
VI -> LOC
Lei Orgânica -> MISC
Governador do Distrito Federal -> LOC
VI -> LOC
Lei Orgânica -> MISC
Decreto -> MISC

In [ ]:
import pandas as pd

In [ ]:
entidades = []
labels = []

for entidade in doc.ents:
    entidades.append(entidade.text)
    labels.append(entidade.label_)

In [ ]:
pd.DataFrame({'Entidade': entidades, 'Label': labels})

                                        Entidade Label
0                                          Órgão   LOC
1                      Conselho Especial\nClasse   ORG
2    DISTRITO FEDERAL E TERRITÓRIOS\nRequerido(s   LOC
3                                      DA CÂMARA   ORG
4           DISTRITO FEDERAL E OUTRO(S)\nRelator   LOC
..                                           ...   ...
851                                   PROCEDENTE   LOC
852                              Leis Distritais  MISC
853                             Lei Complementar  MISC
854                                        omnes   ORG
855                                    D E C I S  MISC

[856 rows x 2 columns]

**Visualizando as entidades no texto**

In [ ]:
modelo_ner.get_pipe('ner').labels

('LOC', 'MISC', 'ORG', 'PER')

In [ ]:
print('LOC', spacy.explain('LOC'))
print('MISC', spacy.explain('MISC'))
print('ORG', spacy.explain('ORG'))
print('PER', spacy.explain('PER'))

LOC Non-GPE locations, mountain ranges, bodies of water
MISC Miscellaneous entities, e.g. events, nationalities, products or works of art
ORG Companies, agencies, institutions, etc.
PER Named person or family.

In [ ]:
spacy.displacy.render(doc, style = 'ent', jupyter=True)

In [ ]:
# !python -m spacy download en_core_web_sm

In [ ]:
# import en_core_web_sm

# modelo_ner_ing = spacy.load('en_core_web_sm')
# modelo_ner_ing.get_pipe('ner').labels

# Tokenizando os dados

In [ ]:
dados = []

# Abre o arquivo ZIP e processa cada arquivo contido nele
with zipfile.ZipFile('/content/texts.zip') as zip:
    for nome_arquivo in zip.namelist():  # Itera sobre a lista de arquivos no ZIP
        with zip.open(nome_arquivo) as arquivo:  # Abre cada arquivo dentro do ZIP
            conteudo = arquivo.read().decode('utf-8')  # Lê e decodifica o conteúdo
            palavras = conteudo.split()  # Divide o conteúdo em palavras
            
            # Adiciona cada palavra junto com o nome do arquivo à lista de dados
            for palavra in palavras:
                dados.append([nome_arquivo, palavra])

# Cria um DataFrame do Pandas com as palavras extraídas e seus arquivos de origem
tabela_palavras = pd.DataFrame(dados, columns=['arquivo', 'palavra'])

In [ ]:
tabela_palavras

                       arquivo              palavra
0                ADI2TJDFT.txt                Órgão
1                ADI2TJDFT.txt                    :
2                ADI2TJDFT.txt             Conselho
3                ADI2TJDFT.txt             Especial
4                ADI2TJDFT.txt               Classe
...                        ...                  ...
193487  ACORDAOTCU25052016.txt  Ministro-Substituto
193488  ACORDAOTCU25052016.txt              AUGUSTO
193489  ACORDAOTCU25052016.txt              SHERMAN
193490  ACORDAOTCU25052016.txt           CAVALCANTI
193491  ACORDAOTCU25052016.txt              Relator

[193492 rows x 2 columns]

In [ ]:
tabela_palavras.to_csv('palavras.csv', index = False, sep = '\t')

**Rotulando os dados no formato IOB**

O formato BIO/IOB ,abreviação de inside, outside, beginning, é um formato de marcação comum para marcar tokens em uma tarefa de agrupamento em linguística computacional (por exemplo, reconhecimento de entidade nomeada).

- O prefixo B antes de uma tag indica que a tag é o início de um pedaço
- O prefixo I antes de uma tag indica que a tag está dentro de um pedaço.
- O prefixo O indica que um token não pertence a nenhuma entidade/pedaço.

Exemplo:


| **palavra** |     **label** |
|------------:|--------------:|
|     ACORDAO |             O |
|    CONSELHO | B-ORGANIZACAO |
|    ESPECIAL | I-ORGANIZACAO |
|          DF |       B-LOCAL |

In [ ]:
tabela_palavras = pd.read_csv('/content/palavras_IOB.tsv', sep = '\t')

In [ ]:
tabela_palavras

                          arquivo     palavra          label
0                     TCU4687.txt       GRUPO              O
1                     TCU4687.txt           I              O
2                     TCU4687.txt      CLASSE              O
3                     TCU4687.txt          II              O
4                     TCU4687.txt          2ª  B-ORGANIZACAO
...                           ...         ...            ...
229272  RR2574407120025020372.txt          de              O
229273  RR2574407120025020372.txt      Chaves              O
229274  RR2574407120025020372.txt    Públicas              O
229275  RR2574407120025020372.txt  Brasileira              O
229276  RR2574407120025020372.txt           .              O

[229277 rows x 3 columns]

In [ ]:
tabela_palavras['label'].unique()

array(['O', 'B-ORGANIZACAO', 'I-ORGANIZACAO', 'B-JURISPRUDENCIA',
       'I-JURISPRUDENCIA', 'B-PESSOA', 'I-PESSOA', 'B-LEGISLACAO',
       'I-LEGISLACAO', 'B-TEMPO', 'B-LOCAL', 'I-LOCAL', 'I-TEMPO'],
      dtype=object)

**Transformando um arquivo para o formato SpaCy**

Formato Spacy:

```
tupla = ('texto', {'entities': [(10, 17, 'ORGANIZACAO'), (25,40, 'PESSOA')]})
```

In [ ]:
grupos_arquivos = tabela_palavras.groupby(by= 'arquivo')

In [ ]:
grupos_arquivos.get_group('ADI2TJDFT.txt')

             arquivo   palavra          label
46105  ADI2TJDFT.txt     Órgão              O
46106  ADI2TJDFT.txt         :              O
46107  ADI2TJDFT.txt  Conselho  B-ORGANIZACAO
46108  ADI2TJDFT.txt  Especial  I-ORGANIZACAO
46109  ADI2TJDFT.txt    Classe              O
...              ...       ...            ...
55911  ADI2TJDFT.txt         a              O
55912  ADI2TJDFT.txt      ação              O
55913  ADI2TJDFT.txt         ,              O
55914  ADI2TJDFT.txt   maioria              O
55915  ADI2TJDFT.txt         .              O

[9811 rows x 3 columns]

In [ ]:
# Obtém os dados do grupo 'ADI2TJDFT.txt' contendo palavras e seus respectivos rótulos
tabela_agrupada = grupos_arquivos.get_group('ADI2TJDFT.txt')[['palavra', 'label']].values

# Inicializa uma string para armazenar o conteúdo do texto extraído
conteudo = ''

# Inicializa um dicionário para armazenar as anotações das entidades
anotacoes = {'entities': []}

# Variáveis para armazenar as posições de início e fim das palavras no texto
inicio_palavra = 0
fim_palavra = 0

# Itera sobre cada palavra e seu respectivo rótulo na tabela agrupada
for texto, label in tabela_agrupada:
    texto = str(texto)  # Converte a palavra para string (caso necessário)
    tamanho_texto = len(texto) + 1  # Calcula o tamanho do texto incluindo um espaço

    # Define os índices de início e fim da palavra no texto concatenado
    inicio_palavra = fim_palavra
    fim_palavra = inicio_palavra + tamanho_texto

    # Se o rótulo não for 'O', adiciona a anotação da entidade
    if label != 'O':
        anotacao = (inicio_palavra, fim_palavra - 1, label)
        anotacoes['entities'].append(anotacao)

    # Concatena a palavra ao conteúdo final, adicionando um espaço entre elas
    conteudo = conteudo + texto + ' '

In [ ]:
conteudo

"Órgão : Conselho Especial Classe : ADI Ação Direta de Inconstitucionalidade N . Processo : 2010002019357-4 Requerente ( s ) : PROCURADORA-GERAL DE JUSTIÇA DO DISTRITO FEDERAL E TERRITÓRIOS Requerido ( s ) : PRESIDENTE DA CÂMARA LEGISLATIVA DO DISTRITO FEDERAL E OUTRO ( S ) Relator : Desembargador LÉCIO RESENDE EMENTA AÇÃO DIRETA DE INCONSTITUCIONALIDADE . LEIS DISTRITAIS N.º 747/1994 E 2018/1998 . LEI COMPLEMENTAR DISTRITAL N.º 380/2001 . INCONSTITUCIONALIDADE FORMAL . LEI ORGÂNICA DO DISTRITO FEDERAL . OCUPAÇÃO DE ÁREA PÚBLICA . COMPETÊNCIA PRIVATIVA DO GOVERNADOR DO DISTRITO FEDERAL . AÇÃO JULGADA PROCEDENTE EM RAZÃO DO VÍCIO FORMAL . Tanto o Decreto n.º 10.829/87 , quanto a Portaria n.º 314/92 , do Instituto Brasileiro do Patrimônio Cultural IBPC , hoje Instituto do Patrimônio Histórico e Artístico Nacional IPHAN , conferem ao Governador do Distrito Federal competência privativa para iniciar o processo legislativo , quando se tratar o tema de uso e ocupação do solo em todo o território do Distrito Federal . ACÓRDÃO Acordam os Desembargadores do Conselho Especial do Tribunal de Justiça do Distrito Federal e dos Territórios LÉCIO RESENDE Relator , JOÃO MAIORISI Vogal , ROMÃO C. OLIVEIRA Vogal , DÁCIO VIEIRA Vogal , SÉRGIO BITTENCOURT Vogal , LECIR MANOEL DA LUZ Vogal , CARMELITA BRASIL Vogal , WALDIR LEÔNCIO LOPES JÚNIOR Vogal , J.J. COSTA CARVALHO Vogal , HUMBERTO ADJUTO ULHÔA Vogal , NÍDIA CORRÊA LIMA Vogal , ANA MARIA DUARTE AMARANTE BRITO Vogal , CRUZ MACEDO - Vogal , ROBERBAL CASEMIRO BELINATI Vogal , SILVÂNIO BARBOSA DOS SANTOS Vogal , OTÁVIO AUGUSTO Vogal , sob a presidência do Desembargador OTÁVIO AUGUSTO , em proferir a seguinte decisão : JULGOU-SE PROCEDENTE A AÇÃO , POR MAIORIA , de acordo com a ata do julgamento e notas taquigráficas . Brasília ( DF ) , 17 de maio de 2011 Des . LÉCIO RESENDE Relator R E L A T Ó R I O A PROCURADORA-GERAL DE JUSTIÇA DO DISTRITO FEDERAL E TERRITÓRIOS propõe Ação Direta de Inconstitucionalidade em face das Leis distritais n.º 747 , de 23 de agosto de 1994 , e 2.018 , de 28 de julho de 1998 , e da Lei Complementar distrital n.º 380 , de 4 de abril de 2001 , que tratam da ocupação de áreas públicas na Região Administrativa do Paranoá RA VII , sob a alegação de afronta aos artigos 3º , item XI , 52 , 100 , itens VI e XXI , e 321 , todos da Lei Orgânica do Distrito Federal LODF . Narra que as normas impugnadas padecem de inconstitucionalidade formal , em razão de disciplinarem matérias de iniciativa legislativa do Chefe do Poder Executivo , as quais não poderiam ter sido propostas por membros do Poder Legislativo , em afronta aos dispositivos acima aludidos . Requer a procedência do pedido para declarar , em tese e com efeitos ex tunc e eficácia erga omnes , a inconstitucionalidade das Leis distritais n.º 747/1994 e 2.018/1998 , bem como da Lei Complementar distrital n.º 380/2001 . Com a inicial vieram os documentos de fls . 11/15 . O Presidente da Câmara Legislativa do Distrito Federal , nas informações de fls . 21/25 , afirma que as matérias tratadas nas leis distritais e na lei complementar impugnadas não estão incluídas no rol daquelas cuja iniciativa de lei é privativa do Governador do Distrito Federal , não havendo se falar em vício de iniciativa . Sustenta que é da Câmara distrital a competência para a matéria constante das leis acoimadas de inconstitucional , conforme previsto no art . 58 , da LODF . O Governador do Distrito Federal presta informações às fls . 27/30 , nas quais concorda com o pedido de declaração de inconstitucionalidade das normas objurgadas , em virtude de serem formalmente inconstitucionais . A manifestação do Procurador-Geral do Distrito Federal , às fls . 32/37 , é no sentido de opinar pela procedência do pedido quanto à alegação de inconstitucionalidade formal das normas impugnadas . Parecer Ministerial de fls . 39/43 oficiando pelo conhecimento da ação direta e pela procedência do pedido deduzido na inicial . É o Relatório . V O T O S O Senhor Desembargador LÉCIO RESENDE Relator A PROCURADORA-GERAL DE JUSTIÇA DO DISTRITO FEDERAL E TERRITÓRIOS propõe Ação Direta de Inconstitucionalidade em face das Leis distritais n.º 747 , de 23 de agosto de 1994 , e 2.018 , de 28 de julho de 1998 , e da Lei Complementar distrital n.º 380 , de 4 de abril de 2001 , que tratam da ocupação de áreas públicas na Região Administrativa do Paranoá RA VII . Em síntese , aduz a requerente que as normas impugnadas padecem de inconstitucionalidade formal , em razão de disciplinarem matérias de iniciativa legislativa do Chefe do Poder Executivo , as quais não poderiam ter sido propostas por membros do Poder Legislativo , em afronta aos artigos 3º , item XI , 52 , 100 , itens VI e XXI , e 321 , todos da Lei Orgânica do Distrito Federal LODF . Requer a procedência do pedido para declarar , em tese e com efeitos ex tunc e eficácia erga omnes , a inconstitucionalidade das citadas normas . Preliminarmente , verifica-se claramente na inicial que , ao cotejar infringência à Lei Orgânica do Distrito Federal , a presente Ação Direta objetiva garantir os princípios expressos na Carta Magna , sendo certo que a via adequada para se discutir a inconstitucionalidade de lei é a Ação Direta de Inconstitucionalidade . Conforme estipula a alínea “ a ” do item I do art . 102 da Carta Magna , as leis e os atos normativos federais ou estaduais podem ser objeto do controle abstrato de normas . O art . 125 , § 2º da Constituição Federal , assim dispõe : “ Art . 125 Os Estados organizarão sua justiça , observados os princípios estabelecidos nesta Constituição . § 1º ( ... ) § 2º - Cabe aos Estados a instituição de representação de inconstitucionalidade de leis ou atos normativos estaduais ou municipais em face da Constituição estadual , vedada a atribuição da legitimação para agir a um único órgão. ” Ficou , assim , instituído o controle abstrato de normas no âmbito estadual . Apesar das peculiaridades que marcam o Distrito Federal , a sua Lei Orgânica constitui instrumento normativo com a finalidade de regular , de modo subordinante e com primazia sobre o ordenamento positivo distrital , a vida político-institucional e jurídico-administrativa do Distrito Federal , entidade integrante da Federação brasileira . Nesse sentido , manifestou-se o eminente Ministro CELSO DE MELLO , quando do seu voto na ADI nº 980-DF , verbis : “ A Lei Orgânica do Distrito Federal constitui instrumento normativo primário destinado a regular , de modo subordinante e com inegável primazia sobre o ordenamento positivo distrital a vida jurídico-administrativa e político-institucional dessa entidade integrante da Federação brasileira . Este ato representa , dentro do sistema positivo , o momento inaugural e fundante da ordem jurídica vigente no âmbito do Distrito Federal . Em uma palavra : A Lei Orgânica equivale , em força , autoridade e eficácia jurídicas , a um verdadeiro estatuto constitucional , essencialmente equiparável às Constituições promulgadas pelos Estados-membros. ” ( DJU de 13 de maio de 1994 , p. 11.337 ) Está , pois , caracterizada a possibilidade do controle da constitucionalidade de leis estaduais ou municipais , tendo como parâmetro a Lei Orgânica do Distrito Federal , pois a mesma equivale em força , autoridade e eficácia jurídicas a um verdadeiro estatuto constitucional , essencialmente equiparável às constituições promulgadas pelos Estados-membros . Finalmente , o excelso Supremo Tribunal Federal , na ADI n.º 1405-6/DF , firmou o entendimento de que o Tribunal de Justiça do Distrito Federal e dos Territórios é competente para julgar as demandas que versem sobre violação , por lei local , da Lei Orgânica do Distrito Federal . Admito , assim , o controle abstrato , quer seja através da Ação Direta de Inconstitucionalidade , quer seja pela Ação Declaratória de Constitucionalidade , pelo Tribunal de Justiça do Distrito Federal e dos Territórios , observados os limites impostos pela Carta Magna quanto ao objeto e ao parâmetro de controle . Ressalte-se que o art . 103 , item III , do Regimento Interno deste egrégio Tribunal de Justiça , legitima o Procurador-Geral de Justiça do Distrito Federal e Territórios à proposição da presente Ação Direta de Inconstitucionalidade . Admito , pois , a presente ação e tenho como ente legitimado a propô-la a Excelentíssima Senhora PROCURADORA-GERAL DE JUSTIÇA DO DISTRITO FEDERAL E TERRITÓRIOS . Passo ao exame do pedido deduzido na inicial . As determinações constantes nas referidas Leis distritais , ora impugnadas , têm o seguinte teor : “ LEI Nº 747 , DE 23 DE AGOSTO DE 1994 ( Autor do Projeto : Deputado Salviano Guimarães ) Promulgação negada pelo Sr. Governador do Distrito Federal ao Projeto de Lei que Autoriza o Poder Executivo a ocupar a Zona de Expansão Urbana do Paranoá 7 ZEU 1 . Faço saber que a Câmara Legislativa do Distrito Federal aprovou e eu promulgo , na forma do § 6º do art . 74 da Lei Orgânica do Distrito Federal , a Lei nº 747 , de 23 de agosto de 1994 : Art . 1º Fica o Poder Executivo autorizado a ocupar a Zona de Expansão Urbana 1 do Paranoá 7 ZEU 1 , nos termos da Lei nº 353 , de 18 de novembro de 1992 , para a fixação dos moradores remanescentes da antiga Vila Paranoá , não contemplados no Programa de Assentamento da População de Baixa Renda . Art . 2º O Poder Executivo procederá ao levantamento para identificar as famílias que deverão ser beneficiadas , nos termos do que estabelece o Decreto nº 11.208 , de 17 de agosto de 1988 , ouvida a Associação de Moradores do Paranoá . Art . 3º A ocupação da Zona de Expansão Urbana 1 do Paranoá 7 ZEU 1 fica condicionada ao zoneamento da Área de Proteção Ambiental do Lago Paranoá . Art . 4º O plano urbanístico deverá ser elaborado pelo Poder Executivo até 90 ( noventa ) dias , contados a partir da publicação desta Lei . Art . 5º Esta Lei entra em vigor na data de sua publicação . Art . 6º Revogam-se as disposições em contrário. ” “ LEI Nº 2.018 , DE 28 DE JULHO DE 1998 ( Autoria do Projeto : Deputado José Edmar ) Destina área para a implementação do Complexo Vivencial e Esportivo do Paranoá , na Região Administrativa do Paranoá RA VII . Faço saber que a Câmara Legislativa do Distrito Federal aprovou , o Governador do Distrito Federal , nos termos do § 3º do art . 74 da Lei Orgânica do Distrito Federal , sancionou , e eu , Presidente da Câmara Legislativa do Distrito Federal , na forma do § 6º do mesmo artigo , promulgo a seguinte Lei : Art . 1º Fica destinada área para a implementação do Complexo Vivencial e Esportivo do Paranoá , na Região Administrativa do Paranoá RA VII , com a seguinte delimitação : I as Quadras 3 e 5 , ao norte ; II a rodovia DF 005 , ao sul ; III a via de acesso à rodovia DF 005 , a leste ; IV os limites da Região Administrativa do Paranoá , a oeste . Art . 2º O Complexo Vivencial e Esportivo do Paranoá tem por finalidade principal a recreação e o lazer e é constituído de : I ginásio de esportes ; II estádio de futebol com demarcação de pista para a prática de atletismo ; III piscinas ; IV pista de cooper ; V áreas de convivência . Art . 3º A área especificada no art . 1º constará do Plano Diretor Local do Paranoá , segundo as diretrizes do Plano Diretor de Ordenamento Territorial do Distrito Federal PDOT . Art . 4º Esta Lei entra em vigor na data de sua publicação . Art . 5º Revogam-se as disposições em contrário. ” “ LEI COMPLEMENTAR Nº 380 , DE 4 DE ABRIL DE 2001 ( Autoria do Projeto : Deputado César Lacerda ) Dispõe sobre a permissão de uso da área que especifica , na Região Administrativa do Paranoá RA VII . O Presidente da Câmara Legislativa do Distrito Federal promulga , nos termos do § 6º do art . 74 da Lei Orgânica do Distrito Federal , a seguinte Lei Complementar , oriunda de Projeto vetado pelo Governador do Distrito Federal e mantido pela Câmara Legislativa do Distrito Federal : Art . 1º Fica permitido o uso comercial de bens e a prestação de serviços em geral na área de 24.414m² ( vinte e quatro mil , quatrocentos e quatorze metros quadrados ) , situada na Região Administrativa do Paranoá RA VII , em conformidade com as seguintes especificações : I localização : DF-001 Estrada Parque Contorno EPCT , km 12,8 , na Região Administrativa do Paranoá RA VII , tendo como perímetro a área que começa no marco cravado no canto da cerca , na divisa da faixa de domínio da Rodovia DF-001 EPCT ; seguindo pela cerca na divisa da faixa de domínio da referida rodovia com o azimute de 158º32'42 '' e a distância de 137,24m ( cento e trinta e sete metros e vinte e quatro centímetros ) ; seguindo à esquerda pela cerca com o azimute de 68º32'42 '' e a distância de 148,75m ( cento e quarenta e oito metros e setenta e cinco centímetros ) ; seguindo à esquerda pela cerca com o azimute de 338º32'42 '' e a distância de 137,24m ( cento e trinta e sete metros e vinte e quatro centímetros ) ; seguindo novamente à esquerda pela cerca com o azimute de 284º32'42 '' e a distância de 148,75m ( cento e quarenta e oito metros e setenta e cinco centímetros ) , chegando ao marco inicial ; II usos permitidos : uso comercial , com atividades de comércio de bens e serviços em geral , com nível de incomodidade 1 e 2 , conforme definido no Anexo II da Lei Complementar nº 90 , de 11 de março de 1998 . Art . 2º Fica permitido para o projeto de parcelamento o uso misto , comércio e residência . Art . 3º A Norma de Edificação , Uso e Gabarito NGB a ser utilizada para efeito desta Lei Complementar é a mesma que vigora atualmente para toda a Região Administrativa do Paranoá RA VII . Art . 4º O Poder Executivo regulamentará esta Lei Complementar no prazo de sessenta dias . Art . 5º Esta Lei Complementar entra em vigor na data de sua publicação . Art . 6º Revogam-se as disposições em contrário. ” Para melhor análise da matéria , confiram-se os dispositivos da Lei Orgânica do Distrito Federal tido como violados : “ Art . 3º São objetivos prioritários do Distrito Federal : ( ... ) XI - zelar pelo conjunto urbanístico de Brasília , tombado sob a inscrição n.º 532 do Livro do Tombo Histórico , respeitadas as definições e critérios constantes do Decreto n.º 10.829 , de 2 de outubro de 1987 , e da Portaria n.º 314 , de 8 de outubro de 1992 , do então Instituto Brasileiro do Patrimônio Cultural - IBPC , hoje Instituto do Patrimônio Histórico e Artístico Nacional - IPHAN . ( Inciso incluído pela Emenda a Lei Orgânica n.º 12 , de 12 de dezembro de 1996 \uf0be DODF de 19.12.96 ) Art . 52 . Cabe ao Poder Executivo a administração dos bens do Distrito Federal , ressalvado à Câmara Legislativa administrar aqueles utilizados em seus serviços e sob sua guarda . Art . 100 . Compete privativamenteao Governador do Distrito Federal : ( ... ) VI iniciar o processo legislativo , na forma e nos casos previstos nesta Lei Orgânica . ( ... ) XXI delegar , por decreto , a qualquer autoridade do Executivo atribuições administrativas que não sejam de sua exclusiva competência ; Art . 321 . É atribuição do Poder Executivo conduzir , no âmbito do processo de planejamento do Distrito Federal , as bases de discussão e elaboração dos planos diretores de ordenamento territorial e locais , bem como sua implementação. ” ( grifo nosso ) As leis distritais e a lei complementar distrital , ora impugnadas , de autoria de Deputados Distritais ( fls . 12 , 14 e 15 ) , padecem do vício de iniciativa , por não ser da competência do Poder Legislativo local a iniciativa de projetos de lei que disponham sobre a ocupação e o uso do solo em todo o território do Distrito Federal . A matéria em questão somente poderia ter sido deduzida por intermédio de projeto de lei iniciado pelo Chefe do Poder Executivo . Tal discussão já restou pacificada nesta egrégia Corte , conforme se pode verificar das ementas abaixo transcritas , sempre no sentido de que compete , privativamente , ao Governador do Distrito Federal , a iniciativa de leis que disponham sobre o uso , a desafetação e a destinação dos bens públicos do Distrito Federal . Vejamos : “ AÇÃO DIRETA DE INCONSTITUCIONALIDADE . LEI COMPLEMENTAR Nº 85/98 . PROJETO DE AUTORIA PARLAMENTAR . COLIDÊNCIA COM A LEI ORGÂNICA DO DISTRITO FEDERAL . RESERVA DE INICIATIVA . VÍCIO FORMAL DE INCONSTITUCIONALIDADE . COMPETÊNCIA PRIVATIVA DO GOVERNADOR DO DISTRITO FEDERAL PARA A PROPOSITURA DE LEIS QUE VERSEM SOBRE ALTERAÇÃO DE USO DE SOLO NO ÂMBITO DO DISTRITO FEDERAL . Conforme precedentes deste Tribunal de Justiça , o Poder Legislativo não pode tomar a iniciativa de elaborar leis para baixar normas que versem sobre alteração de uso de solo no âmbito do Distrito Federal . Nesta seara , a iniciativa de leis é exclusiva do Governador do Distrito Federal , a teor do disposto nos artigos 3º , inciso XI , 52 e 100 , inciso VI , da Lei Orgânica do Distrito Federal . Dessa forma , sendo de iniciativa parlamentar a elaboração da Lei Complementar nº 85/98 , nesta ação impugnada , a Câmara Legislativa do Distrito Federal foi além de sua competência , evidenciando a existência de vício formal , diante da ofensa ao princípio da iniciativa do processo legislativo e da separação dos poderes . Portanto , a proclamação da inconstitucionalidade da Lei Complementar Distrital nº 85 , de 13 de fevereiro de 1998 , com efeitos ex tunc e eficácia erga omnes é medida que se impõe. ” ( ADI 2010002007992-9 , Conselho Especial , Relator Desembargador NATANAEL CAETANO , julgado em 14/9/2010 , DJ-e de 17/11/2010 p. 44 ) ( grifo nosso ) “ AÇÃO DIRETA DE INCONSTITUCIONALIDADE . LEIS COMPLEMENTARES DISTRITAIS Nº 27/97 , 30/97 , 31/97 , 39/97 , 118/98 , 124/98 , 155/98 , 203/99 , 280/00 , 287/00 , 312/00 , 537/02 , 569/02 , 632/02 , 637/02.ALTERAÇÃO DE USO/OCUPAÇÃO OU DESAFETAÇÃO DE ÁREAS PÚBLICAS . INICIATIVA . DEPUTADOS DISTRITAIS . INCONSTITUCIONALIDADE FORMAL . TEORIA DA MODULAÇÃO TEMPORAL . INAPLICABILIDADE . A iniciativa para elaboração de leis que disponham sobre o uso , ocupação e desafetação do solo no Distrito Federal é exclusiva de seu Governador , conforme previsto na Lei Orgânica do Distrito Federal . A modulação dos efeitos da declaração de inconstitucionalidade somente é possível por razões de segurança jurídica ou de excepcional interesse social , em conformidade com o que dispõe o art . 27 da Lei nº 9.868/99 , inocorrentes na hipótese. ” ( ADI 2010002002050-8 , Conselho Especial , Relator Desembargador SÉRGIO BITTENCOURT , julgado em 17/8/2010 , DJ-e de 17/11/2010 p. 44 ) ( grifo nosso ) “ CONSTITUCIONAL E ADMINISTRATIVO . AÇÃO DIRETA DE INCONSTITUCIONALIDADE . LEI COMPLEMENTAR DISTRITAL Nº 788 , DE 02/12/2008 . DESAFETAÇÃO DE ÁREAS INTERSTICIAIS DAS QUADRAS RESIDENCIAIS DE BRAZLÂNDIA-DF ( RA IV ) . INCONSTITUCIONALIDADE FORMAL . EMENDA PARLAMENTAR . OFENSA À LEI ORGÂNICA DO DISTRITO FEDERAL E AOS PRINCÍPIOS ADMINISTRATIVOS . 1 . Reconhece-se o vício formal de inconstitucionalidade apontado na Lei Complementar distrital nº 788 , de 02 de dezembro de 2008 , que , ao dispor sobre a desafetação e a ocupação dos espaços intersticiais das quadras residenciais de Brazlândia-DF Região Administrativa IV , não observou a legitimidade para a propositura de leis que versem sobre a administração de áreas públicas e sobre o uso e a ocupação do solo no Distrito Federal , que é privativa do Chefe do Poder Executivo local . Precedentes desta Corte . 2 . Ação direta de inconstitucionalidade conhecida e julgada procedente. ” ( ADI 2009002013564-6 , Conselho Especial , Relator Desembargador CRUZ MACEDO , julgado em 27/4/2010 , DJ-e de 14/6/2010 p. 79 ) ( grifo nosso ) Ressalte-se , ainda , que cabe ao Distrito Federal respeitar as definições e os critérios insertos no Decreto n.º 10.829/1987 e na Portaria n.º 314/1992 , do Instituto Brasileiro do Patrimônio Histórico e Artístico Nacional IPHAN , e de outro lado é competência privativa do Governador a iniciativa do processo legislativo a respeito do uso e ocupação do solo do Distrito Federal , sendo responsabilidade da Câmara Legislativa apenas a votação de tal projeto . Vejamos a redação do artigo 3º , item XI , da Lei Orgânica 

In [ ]:
anotacoes

{'entities': [(8, 16, 'B-ORGANIZACAO'),
  (17, 25, 'I-ORGANIZACAO'),
  (91, 106, 'B-JURISPRUDENCIA'),
  (158, 166, 'B-LOCAL'),
  (167, 174, 'I-LOCAL'),
  (221, 227, 'B-ORGANIZACAO'),
  (228, 239, 'I-ORGANIZACAO'),
  (240, 242, 'I-ORGANIZACAO'),
  (243, 251, 'I-ORGANIZACAO'),
  (252, 259, 'I-ORGANIZACAO'),
  (298, 303, 'B-PESSOA'),
  (304, 311, 'I-PESSOA'),
  (358, 362, 'B-LEGISLACAO'),
  (363, 373, 'I-LEGISLACAO'),
  (374, 377, 'I-LEGISLACAO'),
  (378, 386, 'I-LEGISLACAO'),
  (389, 398, 'B-LEGISLACAO'),
  (401, 404, 'B-LEGISLACAO'),
  (405, 417, 'I-LEGISLACAO'),
  (418, 427, 'I-LEGISLACAO'),
  (428, 431, 'I-LEGISLACAO'),
  (432, 440, 'I-LEGISLACAO'),
  (474, 477, 'B-LEGISLACAO'),
  (478, 486, 'I-LEGISLACAO'),
  (487, 489, 'I-LEGISLACAO'),
  (490, 498, 'I-LEGISLACAO'),
  (499, 506, 'I-LEGISLACAO'),
  (575, 583, 'B-LOCAL'),
  (584, 591, 'I-LOCAL'),
  (653, 660, 'B-LEGISLACAO'),
  (661, 664, 'I-LEGISLACAO'),
  (665, 674, 'I-LEGISLACAO'),
  (686, 694, 'B-LEGISLACAO'),
  (695, 698, 'I-LEGISLACAO'),
  (699, 705, 'I-LEGISLACAO'),
  (711, 720, 'B-ORGANIZACAO'),
  (721, 731, 'I-ORGANIZACAO'),
  (732, 734, 'I-ORGANIZACAO'),
  (735, 745, 'I-ORGANIZACAO'),
  (746, 754, 'I-ORGANIZACAO'),
  (755, 759, 'B-ORGANIZACAO'),
  (767, 776, 'B-ORGANIZACAO'),
  (777, 779, 'I-ORGANIZACAO'),
  (780, 790, 'I-ORGANIZACAO'),
  (791, 800, 'I-ORGANIZACAO'),
  (801, 802, 'I-ORGANIZACAO'),
  (803, 812, 'I-ORGANIZACAO'),
  (813, 821, 'I-ORGANIZACAO'),
  (822, 827, 'B-ORGANIZACAO'),
  (856, 864, 'B-LOCAL'),
  (865, 872, 'I-LOCAL'),
  (1007, 1015, 'B-LOCAL'),
  (1016, 1023, 'I-LOCAL'),
  (1064, 1072, 'B-ORGANIZACAO'),
  (1073, 1081, 'I-ORGANIZACAO'),
  (1082, 1084, 'I-ORGANIZACAO'),
  (1085, 1093, 'I-ORGANIZACAO'),
  (1094, 1096, 'I-ORGANIZACAO'),
  (1097, 1104, 'I-ORGANIZACAO'),
  (1105, 1107, 'I-ORGANIZACAO'),
  (1108, 1116, 'I-ORGANIZACAO'),
  (1117, 1124, 'I-ORGANIZACAO'),
  (1143, 1148, 'B-PESSOA'),
  (1149, 1156, 'I-PESSOA'),
  (1167, 1171, 'B-PESSOA'),
  (1172, 1180, 'I-PESSOA'),
  (1189, 1194, 'B-PESSOA'),
  (1195, 1197, 'I-PESSOA'),
  (1198, 1206, 'I-PESSOA'),
  (1215, 1220, 'B-PESSOA'),
  (1221, 1227, 'I-PESSOA'),
  (1236, 1242, 'B-PESSOA'),
  (1243, 1254, 'I-PESSOA'),
  (1263, 1268, 'B-PESSOA'),
  (1269, 1275, 'I-PESSOA'),
  (1276, 1278, 'I-PESSOA'),
  (1279, 1282, 'I-PESSOA'),
  (1291, 1300, 'B-PESSOA'),
  (1301, 1307, 'I-PESSOA'),
  (1316, 1322, 'B-PESSOA'),
  (1323, 1330, 'I-PESSOA'),
  (1331, 1336, 'I-PESSOA'),
  (1337, 1343, 'I-PESSOA'),
  (1352, 1356, 'B-PESSOA'),
  (1357, 1362, 'I-PESSOA'),
  (1363, 1371, 'I-PESSOA'),
  (1380, 1388, 'B-PESSOA'),
  (1389, 1395, 'I-PESSOA'),
  (1396, 1401, 'I-PESSOA'),
  (1410, 1415, 'B-PESSOA'),
  (1416, 1422, 'I-PESSOA'),
  (1423, 1427, 'I-PESSOA'),
  (1436, 1439, 'B-PESSOA'),
  (1440, 1445, 'I-PESSOA'),
  (1446, 1452, 'I-PESSOA'),
  (1453, 1461, 'I-PESSOA'),
  (1462, 1467, 'I-PESSOA'),
  (1476, 1480, 'B-PESSOA'),
  (1481, 1487, 'I-PESSOA'),
  (1498, 1506, 'B-PESSOA'),
  (1507, 1515, 'I-PESSOA'),
  (1516, 1524, 'I-PESSOA'),
  (1533, 1541, 'B-PESSOA'),
  (1542, 1549, 'I-PESSOA'),
  (1550, 1553, 'I-PESSOA'),
  (1554, 1560, 'I-PESSOA'),
  (1569, 1575, 'B-PESSOA'),
  (1576, 1583, 'I-PESSOA'),
  (1627, 1633, 'B-PESSOA'),
  (1634, 1641, 'I-PESSOA'),
  (1779, 1787, 'B-LOCAL'),
  (1788, 1789, 'I-LOCAL'),
  (1790, 1792, 'I-LOCAL'),
  (1793, 1794, 'I-LOCAL'),
  (1797, 1799, 'B-TEMPO'),
  (1800, 1802, 'I-TEMPO'),
  (1803, 1807, 'I-TEMPO'),
  (1808, 1810, 'I-TEMPO'),
  (1811, 1815, 'I-TEMPO'),
  (1822, 1827, 'B-PESSOA'),
  (1828, 1835, 'I-PESSOA'),
  (1896, 1904, 'B-LOCAL'),
  (1905, 1912, 'I-LOCAL'),
  (1983, 1987, 'B-LEGISLACAO'),
  (1988, 1998, 'I-LEGISLACAO'),
  (1999, 2002, 'I-LEGISLACAO'),
  (2003, 2006, 'I-LEGISLACAO'),
  (2012, 2014, 'B-TEMPO'),
  (2015, 2017, 'I-TEMPO'),
  (2018, 2024, 'I-TEMPO'),
  (2025, 2027, 'I-TEMPO'),
  (2028, 2032, 'I-TEMPO'),
  (2037, 2042, 'B-LEGISLACAO'),
  (2048, 2050, 'B-TEMPO'),
  (2051, 2053, 'I-TEMPO'),
  (2054, 2059, 'I-TEMPO'),
  (2060, 2062, 'I-TEMPO'),
  (2063, 2067, 'I-TEMPO'),
  (2075, 2078, 'B-LEGISLACAO'),
  (2079, 2091, 'I-LEGISLACAO'),
  (2092, 2101, 'I-LEGISLACAO'),
  (2102, 2105, 'I-LEGISLACAO'),
  (2106, 2109, 'I-LEGISLACAO'),
  (2115, 2116, 'B-TEMPO'),
  (2117, 2119, 'I-TEMPO'),
  (2120, 2125, 'I-TEMPO'),
  (2126, 2128, 'I-TEMPO'),
  (2129, 2133, 'I-TEMPO'),
  (2180, 2186, 'B-LOCAL'),
  (2187, 2201, 'I-LOCAL'),
  (2202, 2204, 'I-LOCAL'),
  (2205, 2212, 'I-LOCAL'),
  (2213, 2215, 'B-LOCAL'),
  (2216, 2219, 'I-LOCAL'),
  (2252, 2259, 'B-LEGISLACAO'),
  (2260, 2262, 'I-LEGISLACAO'),
  (2263, 2264, 'I-LEGISLACAO'),
  (2265, 2269, 'I-LEGISLACAO'),
  (2270, 2272, 'I-LEGISLACAO'),
  (2273, 2274, 'I-LEGISLACAO'),
  (2275, 2277, 'I-LEGISLACAO'),
  (2278, 2279, 'I-LEGISLACAO'),
  (2280, 2283, 'I-LEGISLACAO'),
  (2284, 2285, 'I-LEGISLACAO'),
  (2286, 2291, 'I-LEGISLACAO'),
  (2292, 2294, 'I-LEGISLACAO'),
  (2295, 2296, 'I-LEGISLACAO'),
  (2297, 2300, 'I-LEGISLACAO'),
  (2301, 2302, 'I-LEGISLACAO'),
  (2303, 2304, 'I-LEGISLACAO'),
  (2305, 2308, 'I-LEGISLACAO'),
  (2309, 2310, 'I-LEGISLACAO'),
  (2311, 2316, 'I-LEGISLACAO'),
  (2317, 2319, 'I-LEGISLACAO'),
  (2320, 2323, 'I-LEGISLACAO'),
  (2324, 2332, 'I-LEGISLACAO'),
  (2333, 2335, 'I-LEGISLACAO'),
  (2336, 2344, 'I-LEGISLACAO'),
  (2345, 2352, 'I-LEGISLACAO'),
  (2353, 2357, 'B-LEGISLACAO'),
  (2774, 2778, 'B-LEGISLACAO'),
  (2779, 2789, 'I-LEGISLACAO'),
  (2790, 2793, 'I-LEGISLACAO'),
  (2794, 2802, 'I-LEGISLACAO'),
  (2805, 2815, 'B-LEGISLACAO'),
  (2830, 2833, 'B-LEGISLACAO'),
  (2834, 2846, 'I-LEGISLACAO'),
  (2847, 2856, 'I-LEGISLACAO'),
  (2857, 2860, 'I-LEGISLACAO'),
  (2861, 2869, 'I-LEGISLACAO'),
  (2940, 2946, 'B-ORGANIZACAO'),
  (2947, 2958, 'I-ORGANIZACAO'),
  (2959, 2961, 'I-ORGANIZACAO'),
  (2962, 2970, 'I-ORGANIZACAO'),
  (2971, 2978, 'I-ORGANIZACAO'),
  (3187, 3195, 'B-LOCAL'),
  (3196, 3203, 'I-LOCAL'),
  (3270, 3276, 'B-ORGANIZACAO'),
  (3277, 3286, 'I-ORGANIZACAO'),
  (3388, 3391, 'B-LEGISLACAO'),
  (3392, 3393, 'I-LEGISLACAO'),
  (3394, 3396, 'I-LEGISLACAO'),
  (3397, 3398, 'I-LEGISLACAO'),
  (3399, 3401, 'I-LEGISLACAO'),
  (3402, 3406, 'I-LEGISLACAO'),
  (3425, 3433, 'B-LOCAL'),
  (3434, 3441, 'I-LOCAL'),
  (3663, 3671, 'B-LOCAL'),
  (3672, 3679, 'I-LOCAL'),
  (4001, 4006, 'B-PESSOA'),
  (4007, 4014, 'I-PESSOA'),
  (4057, 4065, 'B-LOCAL'),
  (4066, 4073, 'I-LOCAL'),
  (4144, 4148, 'B-LEGISLACAO'),
  (4149, 4159, 'I-LEGISLACAO'),
  (4160, 4163, 'I-LEGISLACAO'),
  (4164, 4167, 'I-LEGISLACAO'),
  (4173, 4175, 'B-TEMPO'),
  (4176, 4178, 'I-TEMPO'),
  (4179, 4185, 'I-TEMPO'),
  (4186, 4188, 'I-TEMPO'),
  (4189, 4193, 'I-TEMPO'),
  (4198, 4203, 'B-LEGISLACAO'),
  (4209, 4211, 'B-TEMPO'),
  (4212, 4214, 'I-TEMPO'),
  (4215, 4220, 'I-TEMPO'),
  (4221, 4223, 'I-TEMPO'),
  (4224, 4228, 'I-TEMPO'),
  (4236, 4239, 'B-LEGISLACAO'),
  (4240, 4252, 'I-LEGISLACAO'),
  (4253, 4262, 'I-LEGISLACAO'),
  (4263, 4266, 'I-LEGISLACAO'),
  (4267, 4270, 'I-LEGISLACAO'),
  (4276, 4277, 'B-TEMPO'),
  (4278, 4280, 'I-TEMPO'),
  (4281, 4286, 'I-TEMPO'),
  (4287, 4289, 'I-TEMPO'),
  (4290, 4294, 'I-TEMPO'),
  (4341, 4347, 'B-LOCAL'),
  (4348, 4362, 'I-LOCAL'),
  (4363, 4365, 'I-LOCAL'),
  (4366, 4373, 'I-LOCAL'),
  (4374, 4376, 'B-LOCAL'),
  (4377, 4380, 'I-LOCAL'),
  (4663, 4670, 'B-LEGISLACAO'),
  (4671, 4673, 'I-LEGISLACAO'),
  (4674, 4675, 'I-LEGISLACAO'),
  (4676, 4680, 'I-LEGISLACAO'),
  (4681, 4683, 'I-LEGISLACAO'),
  (4684, 4685, 'I-LEGISLACAO'),
  (4686, 4688, 'I-LEGISLACAO'),
  (4689, 4690, 'I-LEGISLACAO'),
  (4691, 4694, 'I-LEGISLACAO'),
  (4695, 4696, 'I-LEGISLACAO'),
  (4697, 4702, 'I-LEGISLACAO'),
  (4703, 4705, 'I-LEGISLACAO'),
  (4706, 4707, 'I-LEGISLACAO'),
  (4708, 4711, 'I-LEGISLACAO'),
  (4712, 4713, 'I-LEGISLACAO'),
  (4714, 4715, 'I-LEGISLACAO'),
  (4716, 4719, 'I-LEGISLACAO'),
  (4720, 4721, 'I-LEGISLACAO'),
  (4722, 4727, 'I-LEGISLACAO'),
  (4728, 4730, 'I-LEGISLACAO'),
  (4731, 4734, 'I-LEGISLACAO'),
  (4735, 4743, 'I-LEGISLACAO'),
  (4744, 4746, 'I-LEGISLACAO'),
  (4747, 4755, 'I-LEGISLACAO'),
  (4756, 4763, 'I-LEGISLACAO'),
  (4764, 4768, 'B-LEGISLACAO'),
  (5001, 5004, 'B-LEGISLACAO'),
  (5005, 5013, 'I-LEGISLACAO'),
  (5014, 5016, 'I-LEGISLACAO'),
  (5017, 5025, 'I-LEGISLACAO'),
  (5026, 5033, 'I-LEGISLACAO'),
  (5104, 5109, 'B-LEGISLACAO'),
  (5110, 5115, 'I-LEGISLACAO'),
  (5260, 5266, 'B-LEGISLACAO'),
  (5267, 5268, 'I-LEGISLACAO'),
  (5269, 5270, 'I-LEGISLACAO'),
  (5271, 5272, 'I-LEGISLACAO'),
  (5273, 5275, 'I-LEGISLACAO'),
  (5276, 5280, 'I-LEGISLACAO'),
  (5281, 5282, 'I-LEGISLACAO'),
  (5283, 5285, 'I-LEGISLACAO'),
  (5286, 5289, 'I-LEGISLACAO'),
  (5290, 5291, 'I-LEGISLACAO'),
  (5292, 5295, 'I-LEGISLACAO'),
  (5296, 5298, 'I-LEGISLACAO'),
  (5299, 5304, 'I-LEGISLACAO'),
  (5305, 5310, 'I-LEGISLACAO'),
  (5416, 5419, 'B-LEGISLACAO'),
  (5420, 5421, 'I-LEGISLACAO'),
  (5422, 5425, 'I-LEGISLACAO'),
  (5426, 5427, 'I-LEGISLACAO'),
  (5428, 5429, 'I-LEGISLACAO'),
  (5430, 5432, 'I-LEGISLACAO'),
  (5433, 5435, 'I-LEGISLACAO'),
  (5436, 5448, 'I-LEGISLACAO'),
  (5449, 5456, 'I-LEGISLACAO'),
  (5568, 5580, 'B-LEGISLACAO'),
  (5944, 5952, 'B-ORGANIZACAO'),
  (5953, 5960, 'I-ORGANIZACAO'),
  (6180, 6188, 'B-ORGANIZACAO'),
  (6189, 6196, 'I-ORGANIZACAO'),
  (6222, 6231, 'B-ORGANIZACAO'),
  (6232, 6242, 'I-ORGANIZACAO'),
  (6295, 6300, 'B-PESSOA'),
  (6301, 6303, 'I-PESSOA'),
  (6304, 6309, 'I-PESSOA'),
  (6334, 6337, 'B-JURISPRUDENCIA'),
  (6338, 6340, 'I-JURISPRUDENCIA'),
  (6341, 6347, 'I-JURISPRUDENCIA'),
  (6363, 6366, 'B-LEGISLACAO'),
  (6367, 6375, 'I-LEGISLACAO'),
  (6376, 6378, 'I-LEGISLACAO'),
  (6379, 6387, 'I-LEGISLACAO'),
  (6388, 6395, 'I-LEGISLACAO'),
  (6628, 6637, 'B-ORGANIZACAO'),
  (6638, 6648, 'I-ORGANIZACAO'),
  (6772, 6780, 'B-LOCAL'),
  (6781, 6788, 'I-LOCAL'),
  (7011, 7013, 'B-TEMPO'),
  (7014, 7016, 'I-TEMPO'),
  (7017, 7021, 'I-TEMPO'),
  (7022, 7024, 'I-TEMPO'),
  (7025, 7029, 'I-TEMPO'),
  (7180, 7183, 'B-LEGISLACAO'),
  (7184, 7192, 'I-LEGISLACAO'),
  (7193, 7195, 'I-LEGISLACAO'),
  (7196, 7204, 'I-LEGISLACAO'),
  (7205, 7212, 'I-LEGISLACAO'),
  (7425, 7432, 'B-ORGANIZACAO'),
  (7433, 7441, 'I-ORGANIZACAO'),
  (7442, 7449, 'I-ORGANIZACAO'),
  (7455, 7458, 'B-JURISPRUDENCIA'),
  (7459, 7462, 'I-JURISPRUDENCIA'),
  (7463, 7472, 'I-JURISPRUDENCIA'),
  (7506, 7514, 'B-ORGANIZACAO'),
  (7515, 7517, 'I-ORGANIZACAO'),
  (7518, 7525, 'I-ORGANIZACAO'),
  (7526, 7528, 'I-ORGANIZACAO'),
  (7529, 7537, 'I-ORGANIZACAO'),
  (7538, 7545, 'I-ORGANIZACAO'),
  (7546, 7547, 'I-ORGANIZACAO'),
  (7548, 7551, 'I-ORGANIZACAO'),
  (7552, 7563, 'I-ORGANIZACAO'),
  (7648, 7651, 'B-LEGISLACAO'),
  (7652, 7660, 'I-LEGISLACAO'),
  (7661, 7663, 'I-LEGISLACAO'),
  (7664, 7672, 'I-LEGISLACAO'),
  (7673, 7680, 'I-LEGISLACAO'),
  (7845, 7853, 'B-ORGANIZACAO'),
  (7854, 7856, 'I-ORGANIZACAO'),
  (7857, 7864, 'I-ORGANIZACAO'),
  (7865, 7867, 'I-ORGANIZACAO'),
  (7868, 7876, 'I-ORGANIZACAO'),
  (7877, 7884, 'I-ORGANIZACAO'),
  (7885, 7886, 'I-ORGANIZACAO'),
  (7887, 7890, 'I-ORGANIZACAO'),
  (7891, 7902, 'I-ORGANIZACAO'),
  (7941, 7946, 'B-LEGISLACAO'),
  (7947, 7952, 'I-LEGISLACAO'),
  (8139, 8147, 'B-LOCAL'),
  (8148, 8155, 'I-LOCAL'),
  (8363, 8371, 'B-LOCAL'),
  (8372, 8379, 'I-LOCAL'),
  (8544, 8547, 'B-LEGISLACAO'),
  (8548, 8550, 'I-LEGISLACAO'),
  (8551, 8554, 'I-LEGISLACAO'),
  (8560, 8562, 'B-TEMPO'),
  (8563, 8565, 'I-TEMPO'),
  (8566, 8572, 'I-TEMPO'),
  (8573, 8575, 'I-TEMPO'),
  (8576, 8580, 'I-TEMPO'),
  (8611, 8619, 'B-PESSOA'),
  (8620, 8629, 'I-PESSOA'),
  (8674, 8682, 'B-LOCAL'),
  (8683, 8690, 'I-LOCAL'),
  (8751, 8755, 'B-LOCAL'),
  (8756, 8758, 'I-LOCAL'),
  (8759, 8767, 'I-LOCAL'),
  (8768, 8774, 'I-LOCAL'),
  (8775, 8777, 'I-LOCAL'),
  (8778, 8785, 'I-LOCAL'),
  (8813, 8819, 'B-ORGANIZACAO'),
  (8820, 8831, 'I-ORGANIZACAO'),
  (8832, 8834, 'I-ORGANIZACAO'),
  (8835, 8843, 'I-ORGANIZACAO'),
  (8844, 8851, 'I-ORGANIZACAO'),
  (8888, 8889, 'B-LEGISLACAO'),
  (8890, 8892, 'I-LEGISLACAO'),
  (8893, 8895, 'I-LEGISLACAO'),
  (8896, 8899, 'I-LEGISLACAO'),
  (8900, 8901, 'I-LEGISLACAO'),
  (8902, 8904, 'I-LEGISLACAO'),
  (8905, 8907, 'I-LEGISLACAO'),
  (8908, 8911, 'I-LEGISLACAO'),
  (8912, 8920, 'I-LEGISLACAO'),
  (8921, 8923, 'I-LEGISLACAO'),
  (8924, 8932, 'I-LEGISLACAO'),
  (8933, 8940, 'I-LEGISLACAO'),
  (8945, 8948, 'B-LEGISLACAO'),
  (8949, 8951, 'I-LEGISLACAO'),
  (8952, 8955, 'I-LEGISLACAO'),
  (8961, 8963, 'B-TEMPO'),
  (8964, 8966, 'I-TEMPO'),
  (8967, 8973, 'I-TEMPO'),
  (8974, 8976, 'I-TEMPO'),
  (8977, 8981, 'I-TEMPO'),
  (9038, 9042, 'B-LOCAL'),
  (9043, 9045, 'I-LOCAL'),
  (9046, 9054, 'I-LOCAL'),
  (9055, 9061, 'I-LOCAL'),
  (9062, 9063, 'I-LOCAL'),
  (9064, 9066, 'I-LOCAL'),
  (9067, 9074, 'I-LOCAL'),
  (9099, 9102, 'B-LEGISLACAO'),
  (9103, 9105, 'I-LEGISLACAO'),
  (9106, 9109, 'I-LEGISLACAO'),
  (9115, 9117, 'B-TEMPO'),
  (9118, 9120, 'I-TEMPO'),
  (9121, 9129, 'I-TEMPO'),
  (9130, 9132, 'I-TEMPO'),
  (9133, 9137, 'I-TEMPO'),
  (9193, 9197, 'B-LOCAL'),
  (9198, 9205, 'I-LOCAL'),
  (9427, 9434, 'B-LEGISLACAO'),
  (9435, 9437, 'I-LEGISLACAO'),
  (9438, 9444, 'I-LEGISLACAO'),
  (9450, 9452, 'B-TEMPO'),
  (9453, 9455, 'I-TEMPO'),
  (9456, 9462, 'I-TEMPO'),
  (9463, 9465, 'I-TEMPO'),
  (9466, 9470, 'I-TEMPO'),
  (9482, 9492, 'B-ORGANIZACAO'),
  (9493, 9495, 'I-ORGANIZACAO'),
  (9496, 9505, 'I-ORGANIZACAO'),
  (9506, 9508, 'I-ORGANIZACAO'),
  (9509, 9516, 'I-ORGANIZACAO'),
  (9542, 9546, 'B-LOCAL'),
  (9547, 9549, 'I-LOCAL'),
  (9550, 9558, 'I-LOCAL'),
  (9559, 9565, 'I-LOCAL'),
  (9566, 9567, 'I-LOCAL'),
  (9568, 9570, 'I-LOCAL'),
  (9571, 9578, 'I-LOCAL'),
  (9622, 9626, 'B-LOCAL'),
  (9627, 9629, 'I-LOCAL'),
  (9630, 9638, 'I-LOCAL'),
  (9639, 9648, 'I-LOCAL'),
  (9649, 9651, 'I-LOCAL'),
  (9652, 9656, 'I-LOCAL'),
  (9657, 9664, 'I-LOCAL'),
  (9922, 9925, 'B-LEGISLACAO'),
  (9926, 9928, 'I-LEGISLACAO'),
  (9929, 9934, 'I-LEGISLACAO'),
  (9940, 9942, 'B-TEMPO'),
  (9943, 9945, 'I-TEMPO'),
  (9946, 9951, 'I-TEMPO'),
  (9952, 9954, 'I-TEMPO'),
  (9955, 9959, 'I-TEMPO'),
  (9992, 9996, 'B-PESSOA'),
  (9997, 10002, 'I-PESSOA'),
  (10089, 10095, 'B-LOCAL'),
  (10096, 10110, 'I-LOCAL'),
  (10111, 10113, 'I-LOCAL'),
  (10114, 10121, 'I-LOCAL'),
  (10122, 10124, 'B-LOCAL'),
  (10125, 10128, 'I-LOCAL'),
  (10148, 10154, 'B-ORGANIZACAO'),
  (10155, 10166, 'I-ORGANIZACAO'),
  (10167, 10169, 'I-ORGANIZACAO'),
  (10170, 10178, 'I-ORGANIZACAO'),
  (10179, 10186, 'I-ORGANIZACAO'),
  (10213, 10221, 'B-LOCAL'),
  (10222, 10229, 'I-LOCAL'),
  (10246, 10247, 'B-LEGISLACAO'),
  (10248, 10250, 'I-LEGISLACAO'),
  (10251, 10253, 'I-LEGISLACAO'),
  (10254, 10257, 'I-LEGISLACAO'),
  (10258, 10259, 'I-LEGISLACAO'),
  (10260, 10262, 'I-LEGISLACAO'),
  (10263, 10265, 'I-LEGISLACAO'),
  (10266, 10269, 'I-LEGISLACAO'),
  (10270, 10278, 'I-LEGISLACAO'),
  (10279, 10281, 'I-LEGISLACAO'),
  (10282, 10290, 'I-LEGISLACAO'),
  (10291, 10298, 'I-LEGISLACAO'),
  (10334, 10340, 'B-ORGANIZACAO'),
  (10341, 10352, 'I-ORGANIZACAO'),
  (10353, 10355, 'I-ORGANIZACAO'),
  (10356, 10364, 'I-ORGANIZACAO'),
  (10365, 10372, 'I-ORGANIZACAO'),
  (10536, 10542, 'B-LOCAL'),
  (10543, 10557, 'I-LOCAL'),
  (10558, 10560, 'I-LOCAL'),
  (10561, 10568, 'I-LOCAL'),
  (10569, 10571, 'B-LOCAL'),
  (10572, 10575, 'I-LOCAL'),
  (10612, 10619, 'B-LOCAL'),
  (10620, 10621, 'I-LOCAL'),
  (10622, 10623, 'I-LOCAL'),
  (10624, 10625, 'I-LOCAL'),
  (10644, 10651, 'B-LOCAL'),
  (10652, 10654, 'I-LOCAL'),
  (10655, 10658, 'I-LOCAL'),
  (10692, 10699, 'B-LOCAL'),
  (10700, 10702, 'I-LOCAL'),
  (10703, 10706, 'I-LOCAL'),
  (10736, 10742, 'B-LOCAL'),
  (10743, 10757, 'I-LOCAL'),
  (10758, 10760, 'I-LOCAL'),
  (10761, 10768, 'I-LOCAL'),
  (11360, 11363, 'B-LEGISLACAO'),
  (11364, 11376, 'I-LEGISLACAO'),
  (11377, 11379, 'I-LEGISLACAO'),
  (11380, 11383, 'I-LEGISLACAO'),
  (11389, 11390, 'B-TEMPO'),
  (11391, 11393, 'I-TEMPO'),
  (11394, 11399, 'I-TEMPO'),
  (11400, 11402, 'I-TEMPO'),
  (11403, 11407, 'I-TEMPO'),
  (11440, 11445, 'B-PESSOA'),
  (11446, 11453, 'I-PESSOA'),
  (11516, 11522, 'B-LOCAL'),
  (11523, 11537, 'I-LOCAL'),
  (11538, 11540, 'I-LOCAL'),
  (11541, 11548, 'I-LOCAL'),
  (11549, 11551, 'B-LOCAL'),
  (11552, 11555, 'I-LOCAL'),
  (11574, 11580, 'B-ORGANIZACAO'),
  (11581, 11592, 'I-ORGANIZACAO'),
  (11593, 11595, 'I-ORGANIZACAO'),
  (11596, 11604, 'I-ORGANIZACAO'),
  (11605, 11612, 'I-ORGANIZACAO'),
  (11638, 11639, 'B-LEGISLACAO'),
  (11640, 11642, 'I-LEGISLACAO'),
  (11643, 11645, 'I-LEGISLACAO'),
  (11646, 11649, 'I-LEGISLACAO'),
  (11650, 11651, 'I-LEGISLACAO'),
  (11652, 11654, 'I-LEGISLACAO'),
  (11655, 11657, 'I-LEGISLACAO'),
  (11658, 11661, 'I-LEGISLACAO'),
  (11662, 11670, 'I-LEGISLACAO'),
  (11671, 11673, 'I-LEGISLACAO'),
  (11674, 11682, 'I-LEGISLACAO'),
  (11683, 11690, 'I-LEGISLACAO'),
  (11768, 11776, 'B-LOCAL'),
  (11777, 11784, 'I-LOCAL'),
  (11800, 11806, 'B-ORGANIZACAO'),
  (11807, 11818, 'I-ORGANIZACAO'),
  (11819, 11821, 'I-ORGANIZACAO'),
  (11822, 11830, 'I-ORGANIZACAO'),
  (11831, 11838, 'I-ORGANIZACAO'),
  (12023, 12029, 'B-LOCAL'),
  (12030, 12044, 'I-LOCAL'),
  (12045, 12047, 'I-LOCAL'),
  (12048, 12055, 'I-LOCAL'),
  (12056, 12058, 'B-LOCAL'),
  (12059, 12062, 'I-LOCAL'),
  (12131, 12137, 'B-LOCAL'),
  (12138, 12145, 'I-LOCAL'),
  (12146, 12152, 'I-LOCAL'),
  (12153, 12161, 'I-LOCAL'),
  (12162, 12166, 'I-LOCAL'),
  (12182, 12188, 'B-LOCAL'),
  (12189, 12203, 'I-LOCAL'),
  (12204, 12206, 'I-LOCAL'),
  (12207, 12214, 'I-LOCAL'),
  (12215, 12217, 'B-LOCAL'),
  (12218, 12221, 'I-LOCAL'),
  (12333, 12340, 'B-LOCAL'),
  (12341, 12347, 'I-LOCAL'),
  (12348, 12352, 'I-LOCAL'),
  (13186, 13191, 'B-LEGISLACAO'),
  (13192, 13194, 'I-LEGISLACAO'),
  (13195, 13197, 'I-LEGISLACAO'),
  (13198, 13201, 'I-LEGISLACAO'),
  (13202, 13214, 'I-LEGISLACAO'),
  (13215, 13217, 'I-LEGISLACAO'),
  (13218, 13220, 'I-LEGISLACAO'),
  (13226, 13228, 'B-TEMPO'),
  (13229, 13231, 'I-TEMPO'),
  (13232, 13237, 'I-TEMPO'),
  (13238, 13240, 'I-TEMPO'),
  (13241, 13245, 'I-TEMPO'),
  (13488, 13494, 'B-LOCAL'),
  (13495, 13509, 'I-LOCAL'),
  (13510, 13512, 'I-LOCAL'),
  (13513, 13520, 'I-LOCAL'),
  (13521, 13523, 'B-LOCAL'),
  (13524, 13527, 'I-LOCAL'),
  (13810, 13813, 'B-LEGISLACAO'),
  (13814, 13822, 'I-LEGISLACAO'),
  (13823, 13825, 'I-LEGISLACAO'),
  (13826, 13834, 'I-LEGISLACAO'),
  (13835, 13842, 'I-LEGISLACAO'),
  (13905, 13913, 'B-ORGANIZACAO'),
  (13914, 13921, 'I-ORGANIZACAO'),
  (13972, 13980, 'B-LOCAL'),
  (14097, 14104, 'B-LEGISLACAO'),
  (14105, 14108, 'I-LEGISLACAO'),
  (14109, 14115, 'I-LEGISLACAO'),
  (14121, 14122, 'B-TEMPO'),
  (14123, 14125, 'I-TEMPO'),
  (14126, 14133, 'I-TEMPO'),
  (14134, 14136, 'I-TEMPO'),
  (14137, 14141, 'I-TEMPO'),
  (14149, 14157, 'B-LEGISLACAO'),
  (14158, 14161, 'I-LEGISLACAO'),
  (14162, 14165, 'I-LEGISLACAO'),
  (14171, 14172, 'B-TEMPO'),
  (14173, 14175, 'I-TEMPO'),
  (14176, 14183, 'I-TEMPO'),
  (14184, 14186, 'I-TEMPO'),
  (14187, 14191, 'I-TEMPO'),
  (14203, 14212, 'B-ORGANIZACAO'),
  (14213, 14223, 'I-ORGANIZACAO'),
  (14224, 14226, 'I-ORGANIZACAO'),
  (14227, 14237, 'I-ORGANIZACAO'),
  (14238, 14246, 'I-ORGANIZACAO'),
  (14249, 14253, 'B-ORGANIZACAO'),
  (14261, 14270, 'B-ORGANIZACAO'),
  (14271, 14273, 'I-ORGANIZACAO'),
  (14274, 14284, 'I-ORGANIZACAO'),
  (14285, 14294, 'I-ORGANIZACAO'),
  (14295, 14296, 'I-ORGANIZACAO'),
  (14297, 14306, 'I-ORGANIZACAO'),
  (14307, 14315, 'I-ORGANIZACAO'),
  (14318, 14323, 'B-ORGANIZACAO'),
  (14349, 14355, 'B-LEGISLACAO'),
  (14356, 14357, 'I-LEGISLACAO'),
  (14358, 14361, 'I-LEGISLACAO'),
  (14362, 14370, 'I-LEGISLACAO'),
  (14371, 14374, 'I-LEGISLACAO'),
  (14375, 14377, 'I-LEGISLACAO'),
  (14383, 14385, 'B-TEMPO'),
  (14386, 14388, 'I-TEMPO'),
  (14389, 14397, 'I-TEMPO'),
  (14398, 14400, 'I-TEMPO'),
  (14401, 14405, 'I-TEMPO'),
  (14416, 14424, 'B-TEMPO'),
  (14490, 14498, 'B-ORGANIZACAO'),
  (14499, 14506, 'I-ORGANIZACAO'),
  (14522, 14528, 'B-ORGANIZACAO'),
  (14529, 14540, 'I-ORGANIZACAO'),
  (14659, 14667, 'B-LOCAL'),
  (14668, 14675, 'I-LOCAL'),
  (15014, 15022, 'B-ORGANIZACAO'),
  (15023, 15030, 'I-ORGANIZACAO'),
  (15492, 15500, 'B-ORGANIZACAO'),
  (15501, 15508, 'I-ORGANIZACAO'),
  (15826, 15834, 'B-LOCAL'),
  (15835, 15842, 'I-LOCAL'),

In [ ]:
conteudo.find('Conselho Especial')

8

In [ ]:
conteudo.find('Conselho Especial') + len('Conselho Especial')

25

# Transformando todos os dados

In [ ]:
arquivos = grupos_arquivos.groups.keys()

In [ ]:
# arquivos

In [ ]:
documentos = []

# Itera sobre cada arquivo na lista de arquivos
for arquivo in arquivos:
    documento = []  # Inicializa a estrutura do documento
    
    # Obtém a tabela de palavras e rótulos associadas ao arquivo
    tabela_agrupada = grupos_arquivos.get_group(arquivo)[['palavra', 'label']].values
    
    # Inicializa variáveis para armazenar o conteúdo e anotações do documento
    conteudo = ''
    anotacoes = {'entities': []}
    
    # Variáveis para rastrear as posições das palavras dentro do texto
    inicio_palavra = 0
    fim_palavra = 0
    
    # Itera sobre cada palavra e seu respectivo rótulo na tabela agrupada
    for texto, label in tabela_agrupada:
        texto = str(texto)  # Converte o texto para string, se necessário
        tamanho_texto = len(texto) + 1  # Calcula o tamanho da palavra incluindo o espaço
        
        # Define os índices de início e fim da palavra dentro do conteúdo total
        inicio_palavra = fim_palavra
        fim_palavra = inicio_palavra + tamanho_texto
        
        # Se a palavra possuir um rótulo diferente de 'O', registra a anotação
        if label != 'O':
            anotacao = (inicio_palavra, fim_palavra - 1, label)
            anotacoes['entities'].append(anotacao)
        
        # Concatena a palavra ao conteúdo do documento, adicionando um espaço
        conteudo = conteudo + texto + ' '
    
    # Estrutura o documento com seu conteúdo e respectivas anotações
    documento = (conteudo, anotacoes)
    
    # Adiciona o documento processado à lista de documentos
    documentos.append(documento)

In [ ]:
# documentos

**Separando dados de treino e validação**

In [ ]:
import random

In [ ]:
random.shuffle(documentos)

In [ ]:
# documentos

In [ ]:
len(documentos)

50

In [ ]:
dados_treino = documentos[:40]
dados_validacao = documentos[40:]

In [ ]:
dados_treino

[("Ementa e Acórdão 11/12/2012 PRIMEIRA TURMA HABEAS CORPUS 110.260 SÃO PAULO RELATOR : MIN . LUIZ FUX PACTE . ( S ) : LAERCIO BRAZ PEREIRA SALES IMPTE . ( S ) : DEFENSORIA PÚBLICA DA UNIÃO PROC . ( A/S ) ( ES ) : DEFENSOR PÚBLICO-GERAL FEDERAL COATOR ( A/S ) ( ES ) : SUPERIOR TRIBUNAL DE JUSTIÇA EMENTA : PROCESSUAL PENAL E CONSTITUCIONAL . HABEAS CORPUS SUBSTITUTIVO DE RECURSO ORDINÁRIO CONSTITUCIONAL . COMPETÊNCIA DO SUPREMO TRIBUNAL PARA JULGAR HABEAS CORPUS : CF , ART . 102 , I , ‘ D ’ E ‘ I ’ . ROL TAXATIVO . MATÉRIA DE DIREITO ESTRITO . INTERPRETAÇÃO EXTENSIVA : PARADOXO . ORGANICIDADE DO DIREITO . AUSÊNCIA DE TERATOLOGIA OU ERROR IN JUDICANDO NO ATO IMPUGNADO . INVIABILIDADE DA ATUAÇÃO , EX OFFICIO , DO SUPREMO TRIBUNAL FEDERAL . HOMICÍDIOS DUPLAMENTE QUALIFICADOS , nan FORMA TENTADA , PRATICADOS CONTRA CÔNJUGE E DESCENDENTE ( CP , ART . 121 , § 2 º , II E IV , C / C ART . 61 , II , E , E 14 , II ) . PRONÚNCIA . EXCESSO DE LINGUAGEM QUANTO AOS CRIMES E ÀS QUALIFICADORAS . INOCORRÊNCIA : MERA REPRODUÇÃO DOS INTERROGATÓRIOS . ANIMUS NECANDI : LINGUAGEM COMEDIDA ( ART . 413 , § 1 º , DO DO CPP . EQUILÍBRIO COM A PRETENDIDA DESCLASSIFICAÇÃO DOS HOMICÍDIOS PARA LESÕES CORPORAIS . FUNDAMENTAÇÃO DAS DECISÕES DO PODER JUDICIÁRIO . ART . 93 , IX , DA CF . 1 . A competência originária do Supremo Tribunal Federal para conhecer e julgar habeas corpus está definida , taxativamente , no artigo 102 , inciso I , alíneas “ d ” e “ i ” , da Constituição Federal , sendo certo que o paciente não está inserido em nenhuma das hipóteses sujeitas à jurisdição desta Corte . 2 . Inexistente teratologia ou error in judicando no acórdão impugnado , resta inviabilizada a atuação ex officio do Supremo Tribunal Federal . 3 . O artigo 413 do Código de Processo Penal determina que “ O juiz , fundamentadamente , pronunciará o acusado , se convencido da materialidade do fato e da existência de indícios suficientes de autoria ou de participação ” , ao Supremo Tribunal Federal Documento assinado digitalmente conforme MP n° 2.200-2/2001 de 24/08/2001 , que institui a Infraestrutura de Chaves Públicas Brasileira - ICP-Brasil . O documento pode ser acessado no endereço eletrônico http : //www.stf.jus.br/portal/autenticacao/ sob o número 3373812 . Supremo Tribunal Federal Inteiro Teor do Acórdão - Página 1 de 20 Ementa e Acórdão HC 110260 / SP passo que seu § 1º estabelece que “ A fundamentação da pronúncia limitar-seá à indicação da materialidade do fato e da existência de indícios suficientes de autoria ou de participação , devendo o juiz declarar o dispositivo legal em que julgar incurso o acusado e especificar as circunstâncias qualificadoras e as causas de aumento de pena ” . 4 . In casu , o paciente foi pronunciado por homicídios duplamente qualificados motivo fútil e emboscada - , na forma tentada ( CP , art . 121 , § 2º , II e IV , c/c art . 14 , II ) , praticados contra a esposa e o filho , tendo as instâncias precedentes refutado a alegação de excesso de linguagem na sentença de pronúncia . 5 . A fundamentação da sentença de pronúncia não se desbordou do figurino legal , por isso não ostenta a nulidade ora suscitada , ressaindo nítido que o Magistrado ateve-se ao relato dos fatos , revelados nos interrogatórios das vítimas , para concluir , fundamentadamente , pela existência de indícios suficientes de autoria e de materialidade , como exigido pelo artigo 413 , por imposição do disposto no art . 93 , IX , da constituição Federal . Precedentes : HC 89420/RS - Relator Min . EROS GRAU , 2ª Turma , DJ de 07/12/2006 6 . A afirmação , na pronúncia , tida como verbalmente excessiva , de que “ a integridade corporal da vítima com disparos de revólver contra região vital do corpo dela o acusado revelou animus necandi , na medida em que essa não é a conduta de quem objetiva somente lesionar ou assustar pois esse resultado poderia ser obtido de maneira menos ofensiva , por exemplo , mediante agressão com as mãos ou utilizando algum instrumento sem potencialidade letal ” , deve ser compreendida como mera resposta ao argumento de que a intenção do réu era a de causar lesões corporais . 7 . O simples relato dos fatos , sem a emissão de juízo de valor ou de afirmações cabais a respeito da materialidade ou da existência de indícios suficientes de autoria , atende ao disposto nos arts . 413 , § 1º , do CPP e 93 , IX , da Constituição Federal . 8 . Habeas corpus julgado extinto . A C Ó R D Ã O Vistos , relatados e discutidos estes autos , acordam os Ministros da2 Supremo Tribunal Federal Documento assinado digitalmente conforme MP n° 2.200-2/2001 de 24/08/2001 , que institui a Infraestrutura de Chaves Públicas Brasileira - ICP-Brasil . O documento pode ser acessado no endereço eletrônico http : //www.stf.jus.br/portal/autenticacao/ sob o número 3373812 . Supremo Tribunal Federal HC 110260 / SP passo que seu § 1º estabelece que “ A fundamentação da pronúncia limitar-seá à indicação da materialidade do fato e da existência de indícios suficientes de autoria ou de participação , devendo o juiz declarar o dispositivo legal em que julgar incurso o acusado e especificar as circunstâncias qualificadoras e as causas de aumento de pena ” . 4 . In casu , o paciente foi pronunciado por homicídios duplamente qualificados motivo fútil e emboscada - , na forma tentada ( CP , art . 121 , § 2º , II e IV , c/c art . 14 , II ) , praticados contra a esposa e o filho , tendo as instâncias precedentes refutado a alegação de excesso de linguagem na sentença de pronúncia . 5 . A fundamentação da sentença de pronúncia não se desbordou do figurino legal , por isso não ostenta a nulidade ora suscitada , ressaindo nítido que o Magistrado ateve-se ao relato dos fatos , revelados nos interrogatórios das vítimas , para concluir , fundamentadamente , pela existência de indícios suficientes de autoria e de materialidade , como exigido pelo artigo 413 , por imposição do disposto no art . 93 , IX , da constituição Federal . Precedentes : HC 89420/RS - Relator Min . EROS GRAU , 2ª Turma , DJ de 07/12/2006 6 . A afirmação , na pronúncia , tida como verbalmente excessiva , de que “ a integridade corporal da vítima com disparos de revólver contra região vital do corpo dela o acusado revelou animus necandi , na medida em que essa não é a conduta de quem objetiva somente lesionar ou assustar pois esse resultado poderia ser obtido de maneira menos ofensiva , por exemplo , mediante agressão com as mãos ou utilizando algum instrumento sem potencialidade letal ” , deve ser compreendida como mera resposta ao argumento de que a intenção do réu era a de causar lesões corporais . 7 . O simples relato dos fatos , sem a emissão de juízo de valor ou de afirmações cabais a respeito da materialidade ou da existência de indícios suficientes de autoria , atende ao disposto nos arts . 413 , § 1º , do CPP e 93 , IX , da Constituição Federal . 8 . Habeas corpus julgado extinto . A C Ó R D Ã O Vistos , relatados e discutidos estes autos , acordam os Ministros da2 Supremo Tribunal Federal Documento assinado digitalmente conforme MP n° 2.200-2/2001 de 24/08/2001 , que institui a Infraestrutura de Chaves Públicas Brasileira - ICP-Brasil . O documento pode ser acessado no endereço eletrônico http : //www.stf.jus.br/portal/autenticacao/ sob o número 3373812 . Inteiro Teor do Acórdão - Página 2 de 20 Ementa e Acórdão HC 110260 / SP Primeira Turma do Supremo Tribunal Federal , sob a Presidência do Senhor Ministro Dias Toffoli , na conformidade da ata de julgamento e das notas taquigráficas , por unanimidade de votos , em julgar extinta a ordem de habeas corpus por inadequação da via processual , nos termos do voto do Relator . Brasília , 11 de dezembro de 2012 . LUIZ FUX Relator Documento assinado digitalmente 3 Supremo Tribunal Federal Documento assinado digitalmente conforme MP n° 2.200-2/2001 de 24/08/2001 , que institui a Infraestrutura de Chaves Públicas Brasileira - ICP-Brasil . O documento pode ser acessado no endereço eletrônico http : //www.stf.jus.br/portal/autenticacao/ sob o número 3373812 . Supremo Tribunal Federal HC 110260 / SP Primeira Turma do Supremo Tribunal Federal , sob a Presidência do Senhor Ministro Dias Toffoli , na conformidade da ata de julgamento e das notas taquigráficas , por unanimidade de votos , em julgar extinta a ordem de habeas corpus por inadequação da via processual , nos termos do voto do Relator . Brasília , 11 de dezembro de 2012 . LUIZ FUX Relator Documento assinado digitalmente 3 Supremo Tribunal Federal Documento assinado digitalmente conforme MP n° 2.200-2/2001 de 24/08/2001 , que institui a Infraestrutura de Chaves Públicas Brasileira - ICP-Brasil . O documento pode ser acessado no endereço eletrônico http : //www.stf.jus.br/portal/autenticacao/ sob o número 3373812 . Inteiro Teor do Acórdão - Página 3 de 20 Relatório 11/12/2012 PRIMEIRA TURMA HABEAS CORPUS 110.260 SÃO PAULO RELATOR : MIN . LUIZ FUX PACTE . ( S ) : LAERCIO BRAZ PEREIRA SALES IMPTE . ( S ) : DEFENSORIA PÚBLICA DA UNIÃO PROC . ( A/S ) ( ES ) : DEFENSOR PÚBLICO-GERAL FEDERAL COATOR ( A/S ) ( ES ) : SUPERIOR TRIBUNAL DE JUSTIÇA R E L A T Ó R I O O SENHOR MINISTRO LUIZ FUX ( RELATOR ) : Trata-se de habeas corpus , com pedido de liminar , impetrado contra acórdão prolatado pela Quinta Turma do Superior Tribunal de Justiça , cuja ementa possui o seguinte teor : HABEAS CORPUS . HOMICÍDIO QUALIFICADO TENTADO . MOTIVO FÚTIL . RECURSO QUE DIFICULTOU A DEFESA DA VÍTIMA . DENÚNCIA . PEÇA INAUGURAL QUE ATENDE AOS REQUISITOS LEGAIS EXIGIDOS . INICIAL ACUSATÓRIA QUE DESCREVE CRIME EM TESE E SUAS QUALIFICADORAS . AMPLA DEFESA GARANTIDA . EXCLUSÃO . IMPOSSIBILIDADE . COMPETÊNCIA DO CONSELHO DE SENTENÇA . INÉPCIA NÃO EVIDENCIADA . 1 . Não pode ser acoimada de inepta a denúncia formulada em obediência aos requisitos traçados no art . 41 do CPP , descrevendo perfeitamente o fato típico imputado , crime em tese , com todas as suas circunstâncias , atribuindo-o ao paciente , terminando por classificá-lo , ao indicar o ilícito supostamente infringido . 2 . Se a vestibular acusatória narra em que consistiu a ação criminosa do paciente no delito em que lhe incursionou , bem como as qualificadoras que lhe são atribuídas , permitindo o exercício da ampla defesa , é inviável acolher-se a pretensão de invalidade da peça vestibular . Supremo Tribunal Federal Documento assinado digitalmente conforme MP n° 2.200-2/2001 de 24/08/2001 , que institui a Infraestrutura de Chaves Públicas Brasileira - ICP-Brasil . O documento pode ser acessado no endereço eletrônico http : //www.stf.jus.br/portal/autenticacao/ sob o número 3373813 . Supremo Tribunal Federal 11/12/2012 PRIMEIRA TURMA HABEAS CORPUS 110.260 SÃO PAULO RELATOR : MIN . LUIZ FUX PACTE . ( S ) : LAERCIO BRAZ PEREIRA SALES IMPTE . ( S ) : DEFENSORIA PÚBLICA DA UNIÃO PROC . ( A/S ) ( ES ) : DEFENSOR PÚBLICO-GERAL FEDERAL COATOR ( A/S ) ( ES ) : SUPERIOR TRIBUNAL DE JUSTIÇA R E L A T Ó R I O O SENHOR MINISTRO LUIZ FUX ( RELATOR ) : Trata-se de habeas corpus , com pedido de liminar , impetrado contra acórdão prolatado pela Quinta Turma do Superior Tribunal de Justiça , cuja ementa possui o seguinte teor : HABEAS CORPUS . HOMICÍDIO QUALIFICADO TENTADO . MOTIVO FÚTIL . RECURSO QUE DIFICULTOU A DEFESA DA VÍTIMA . DENÚNCIA . PEÇA INAUGURAL QUE ATENDE AOS REQUISITOS LEGAIS EXIGIDOS . INICIAL ACUSATÓRIA QUE DESCREVE CRIME EM TESE E SUAS QUALIFICADORAS . AMPLA DEFESA GARANTIDA . EXCLUSÃO . IMPOSSIBILIDADE . COMPETÊNCIA DO CONSELHO DE SENTENÇA . INÉPCIA NÃO EVIDENCIADA . 1 . Não pode ser acoimada de inepta a denúncia formulada em obediência aos requisitos traçados no art . 41 do CPP , descrevendo perfeitamente o fato típico imputado , crime em tese , com todas as suas circunstâncias , atribuindo-o ao paciente , terminando por classificá-lo , ao indicar o ilícito supostamente infringido . 2 . Se a vestibular acusatória narra em que consistiu a ação criminosa do paciente no delito em que lhe incursionou , bem como as qualificadoras que lhe são atribuídas , permitindo o exercício da ampla defesa , é inviável acolher-se a pretensão de invalidade da peça vestibular . Supremo Tribunal Federal Documento assinado digitalmente conforme MP n° 2.200-2/2001 de 24/08/2001 , que institui a Infraestrutura de Chaves Públicas Brasileira - ICP-Brasil . O documento pode ser acessado no endereço eletrônico http : //www.stf.jus.br/portal/autenticacao/ sob o número 3373813 . Inteiro Teor do Acórdão - Página 4 de 20 Relatório HC 110260 / SP 3 . A análise acerca da motivação e forma como foram praticadas as condutas supostamente delituosas é tarefa que deve ser feita de acordo com a narrativa dos fatos constantes da denúncia , com o auxílio do conjunto fático-probatório produzido no âmbito do devido processo legal , a cargo da Corte Popular , juiz natural da causa , o que impede a afirmação ou exclusão das qualificadoras por este Sodalício . TRIBUNAL DO JÚRI . PRONÚNCIA . EXCESSO DE LINGUAGEM nan ANÁLISE DO MÉRITO DA CAUSA E nan APRECIAÇÃO CRÍTICA E VALORATIVA DO ELENCO PROBATÓRIO . INFLUÊNCIA NO ÂNIMO DOS JURADOS . PROVA DA MATERIALIDADE E INDÍCIOS DA AUTORIA DELITIVA . EXISTÊNCIA . REFERÊNCIA À CIRCUNSTÂNCIA AGRAVANTE nan PARTE DISPOSITIVA . AUSÊNCIA DE JUÍZO DE VALOR . NULIDADE RECHAÇADA . COAÇÃO ILEGAL INEXISTENTE . ORDEM DENEGADA . 1 . Embora uma das alterações significantes no procedimento do julgamento dos crimes dolosos contra a vida , com o advento da Lei n . 11.689/2008 , tenha sido a proibição das partes se referirem em Plenário à decisão de pronúncia ( art . 478 , I , do CPP ) , é certo que os jurados , caso solicitem , terão acesso aos autos e , consequentemente , à provisional objurgada ( art . 480 , § 3º , do CPP ) , razão pela qual vislumbra-se o risco de influência no ânimo do Tribunal Popular . 2 . Independentemente de considerar-se relativa ou absoluta a nulidade apontada , não caracteriza constrangimento ilegal a prolação de pronúncia na qual se indica a materialidade do crime e os indícios da autoria delitiva , mesmo que diversos , pois a quantidade de elementos neste sentido não configuram excesso de linguagem , se o decisum provisional não efetuou análise crítica e valorativa do contexto probatório a ponto de influenciar na decisão do Conselho de Sentença . 3 . A simples menção de circunstância agravante na parte2 Supremo Tribunal Federal Documento assinado digitalmente conforme MP n° 2.200-2/2001 de 24/08/2001 , que institui a Infraestrutura de Chaves Públicas Brasileira - ICP-Brasil . O documento pode ser acessado no endereço eletrônico http : //www.stf.jus.br/portal/autenticacao/ sob o número 3373813 . Supremo Tribunal Federal HC 110260 / SP 3 . A análise acerca da motivação e forma como foram praticadas as condutas supostamente delituosas é tarefa que deve ser feita de acordo com a narrativa dos fatos constantes da denúncia , com o auxílio do conjunto fático-probatório produzido no âmbito do devido processo legal , a cargo da Corte Popular , juiz natural da causa , o que impede a afirmação ou exclusão das qualificadoras por este Sodalício . TRIBUNAL DO JÚRI . PRONÚNCIA . EXCESSO DE LINGUAGEM nan ANÁLISE DO MÉRITO DA CAUSA E nan APRECIAÇÃO CRÍTICA E VALORATIVA DO ELENCO PROBATÓRIO . INFLUÊNCIA NO ÂNIMO DOS JURADOS . PROVA DA MATERIALIDADE E INDÍCIOS DA AUTORIA DELITIVA . EXISTÊNCIA . REFERÊNCIA À CIRCUNSTÂNCIA AGRAVANTE nan PARTE DISPOSITIVA . AUSÊNCIA DE JUÍZO DE VALOR . NULIDADE RECHAÇADA . COAÇÃO ILEGAL INEXISTENTE . ORDEM DENEGADA . 1 . Embora uma das alterações significantes no procedimento do julgamento dos crimes dolosos contra a vida , com o advento da Lei n . 11.689/2008 , tenha sido a proibição das partes se referirem em Plenário à decisão de pronúncia ( art . 478 , I , do CPP ) , é certo que os jurados , caso solicitem , terão acesso aos autos e , consequentemente , à provisional objurgada ( art . 480 , § 3º , do CPP ) , razão pela qual vislumbra-se o risco de influência no ânimo do Tribunal Popular . 2 . Independentemente de considerar-se relativa ou absoluta a nulidade apontada , não caracteriza constrangimento ilegal a prolação de pronúncia na qual se indica a materialidade do crime e os indícios da autoria delitiva , mesmo que diversos , pois a quantidade de elementos neste sentido não configuram excesso de linguagem , se o decisum provisional não efetuou análise crítica e valorativa do contexto probatório a ponto de influenciar na decisão do Conselho de Sentença . 3 . A simples menção de circunstância agravante na parte2 Supremo Tribunal Federal Documento assinado digitalmente conforme MP n° 2.200-2/2001 de 24/08/2001 , que institui a Infraestrutura de Chaves Públicas Brasileira - ICP-Brasil . O documento pode ser acessado no endereço eletrônico http : //www.stf.jus.br/portal/autenticacao/ sob o número 3373813 . Inteiro Teor do Acórdão - Página 5 de 20 Relatório HC 110260 / SP dispositiva da decisão de pronúncia - mera reprodução da capitulação dada aos fatos pelo Ministério Público na exordial acusatória - , desprovida de juízo de valor acerca da sua caracterização , não tem o condão de exercer qualquer influência na convicção a ser formada pelos integrantes do Conselho de Sentença , razão pela qual não se evidencia o alegado constrangimento ilegal . 4 . Ordem denegada . O paciente foi pronunciado , em 23/03/2004 , pelo crime tipificado no artigo 121 , § 2º , incisos II e IV , c/c os artigos 61 , inciso II , alínea e , e 14 , II ( por duas vezes ) , todos do Código Penal . A Defensoria Pública da União alega , em síntese , excesso de linguagem , visto que o Juiz ( ... ) ao pronunciá-lo , externou “ juízo de valor e certeza acerca dos fatos e da autoria , e , de igual modo , em relação à presença da circunstância agravante ( art . 61 , II , 1e1 do CP , excedendo-se , igualmente , na análise crítica e valorativa das provas constantes dos autos , restando por subtrair as atribuições do juízo natural do caso , o Conselho de Sentença ” . Requer seja concedida a liminar para suspender o efeitos do acórdão impugnado e , consequentemente , o acórdão prolatado no Recurso em Sentido Estrito n . 439.398-3/8-00 . Pleiteia , no mérito , a concessão definitiva da ordem a fim de assegurar a liberdade do paciente até o trânsito em julgado do processo originário . A liminar foi indeferida . A PGR manifestou-se no sentido denegação da ordem em parecer sintetizado nestes termos : “ HABEAS CORPUS . HOMICÍDIO QUALIFICADO . TENTATIVA . SENTENÇA DE PRONÚNCIA . ALEGAÇÃO DE EXCESSO DE LINGUAGEM . SENTENÇA QUE NÃO3 Supremo Tribunal Federal Documento assinado digitalmente conforme MP n° 2.200-2/2001 de 24/08/2001 , que institui a Infraestrutura de Chaves Públicas Brasileira - ICP-Brasil . O documento pode ser acessado no endereço eletrônico http : //www.stf.jus.br/portal/autenticacao/ sob o número 3373813 . Supremo Tribunal Federal HC 110260 / SP dispositiva da decisão de pronúncia - mera reprodução da capitulação dada aos fatos pelo Ministério Público na exordial acusatória - , desprovida de juízo de valor acerca da sua caracterização , não tem o condão de exercer qualquer influência na convicção a ser formada pelos integrantes do Conselho de Sentença , razão pela qual não se evidencia o alegado constrangimento ilegal . 4 . Ordem denegada . O paciente foi pronunciado , em 23/03/2004 , pelo crime tipificado no artigo 121 , § 2º , incisos II e IV , c/c os artigos 61 , inciso II , alínea e , e 14 , II ( por duas vezes ) , todos do Código Penal . A Defensoria Pública da União alega , em síntese , excesso de linguagem , visto que o Juiz ( ... ) ao pronunciá-lo , externou “ juízo de valor e certeza acerca dos fatos e da autoria , e , de igual modo , em relação à presença da circunstância agravante ( art . 61 , II , 1e1 do CP , excedendo-se , igualmente , na análise crítica e valorativa das provas constantes dos autos , restando por subtrair as atribuições do juízo natural do caso , o Conselho de Sentença ” . Requer seja concedida a liminar para suspender o efeitos do acórdão impugnado e , consequentemente , o a

# Construindo função de treinamento

In [ ]:
from tqdm import tqdm
from spacy.training import Example

In [ ]:
def treinar_modelo_ner(dados_treino, dados_validacao, epocas):
    # Carrega um modelo pré-treinado da spaCy para o idioma português
    modelo = spacy.load('pt_core_news_sm')
    
    # Verifica se o pipeline de NER já existe no modelo
    if 'ner' not in modelo.pipe_names:
        ner = modelo.create_pipe('ner')  # Cria um novo pipeline de NER
        modelo.add_pipe(ner, last=True)  # Adiciona o pipeline ao modelo
    else:
        ner = modelo.get_pipe('ner')  # Obtém o pipeline de NER existente
    
    # Adiciona rótulos das entidades ao pipeline de NER
    for _, anotacoes in dados_treino:
        for ent in anotacoes.get('entities'):
            ner.add_label(ent[2])
    
    # Desativa outros pipelines para treinar apenas o NER
    outros_pipelines = [pipeline for pipeline in modelo.pipe_names if pipeline != 'ner']
    with modelo.disable_pipes(*outros_pipelines):
        
        # Define uma semente para garantir reprodutibilidade nos resultados
        spacy.util.fix_random_seed()
        
        # Cria um otimizador para o modelo
        otimizador = modelo.create_optimizer()
        
        # Loop de treinamento por número de épocas
        for epoca in tqdm(range(epocas), desc='Treinando o modelo'):
            
            random.seed(10)  # Define semente para aleatoriedade controlada
            random.shuffle(dados_treino)  # Embaralha os dados de treinamento
            losses = {'ner': 0.0}  # Inicializa a variável de perda do modelo
            
            # Treina o modelo com os dados de treinamento
            for textos, anotacoes in dados_treino:
                exemplo = Example.from_dict(modelo.make_doc(textos), anotacoes)  # Cria um exemplo para treinamento
                modelo.update([exemplo], drop=0.2, sgd=otimizador, losses=losses)  # Atualiza o modelo
            
            # Exibe a perda média por amostra na época atual
            print(f'\nÉpoca {epoca+1} - Loss médio de treino: {losses["ner"] / len(dados_treino)}')
            
            # Inicializa a perda de validação
            val_losses = {'ner': 0.0}
            exemplos = []
            
            # Cria exemplos de validação
            for textos, anotacoes in dados_validacao:
                exemplo = Example.from_dict(modelo.make_doc(textos), anotacoes)
                exemplos.append(exemplo)
            
            # Avalia o modelo nos dados de validação
            for exemplo in exemplos:
                modelo.update([exemplo], sgd=None, drop=0, losses=val_losses)
            
            # Exibe a perda média de validação na época atual
            print(f'\nÉpoca {epoca+1} - Loss médio de validação: {val_losses["ner"] / len(dados_validacao)}')
    
    return modelo

**Treinando e salvando o modelo**

In [ ]:
modelo_ner = treinar_modelo_ner(dados_treino, dados_validacao, epocas = 30)

In [ ]:
modelo_ner.to_disk('/content/modelo')

In [ ]:
!zip -r /content/modelo.zip /content/modelo

# Carregando e testando o modelo

In [ ]:
!unzip /content/modelo.zip

In [ ]:
modelo_ner = spacy.load('/content/content/modelo')

In [ ]:
doc = modelo_ner('João nasceu no dia 10/04/2010 em Florianópolis')

In [ ]:
for entidade in doc.ents:
    print(f'{entidade.text} -> {entidade.label_}')

João -> B-PESSOA
10/04/2010 -> B-TEMPO
Florianópolis -> B-LOCAL

In [ ]:
spacy.displacy.render(doc, style = 'ent', jupyter = True)

In [ ]:
with open('/content/20150110436469APC.txt', encoding = 'utf-8') as arquivo:
    texto = arquivo.read()

In [ ]:
# print(texto)

In [ ]:
doc = modelo_ner(texto)

spacy.displacy.render(doc, style = 'ent', jupyter = True)

**Alterando a visualização das cores**

In [ ]:
rotulos = list(modelo_ner.get_pipe('ner').labels)
rotulos

['B-JURISPRUDENCIA',
 'B-LEGISLACAO',
 'B-LOCAL',
 'B-ORGANIZACAO',
 'B-PESSOA',
 'B-TEMPO',
 'I-JURISPRUDENCIA',
 'I-LEGISLACAO',
 'I-LOCAL',
 'I-ORGANIZACAO',
 'I-PESSOA',
 'I-TEMPO',
 'LOC',
 'MISC',
 'ORG',
 'PER']

Cores:

- Azul: #F0F8FF
- Vermelho: #FA8072
- Verde: #98FB98
- Roxo: #DDA0DD
- Amarelo: #F0E68C
- Rosa: #FFB6C1
- Cinza: #D3D3D3

In [ ]:
cores = {
'B-JURISPRUDENCIA': '#F0F8FF',
 'B-LEGISLACAO': '#FA8072',
 'B-LOCAL': '#98FB98',
 'B-ORGANIZACAO': '#DDA0DD',
 'B-PESSOA': '#F0E68C',
 'B-TEMPO': '#FFB6C1',
 'I-JURISPRUDENCIA': '#F0F8FF',
 'I-LEGISLACAO': '#FA8072',
 'I-LOCAL': '#98FB98',
 'I-ORGANIZACAO': '#DDA0DD',
 'I-PESSOA': '#F0E68C',
 'I-TEMPO': '#FFB6C1',
 'LOC': '#D3D3D3',
 'MISC': '#D3D3D3',
 'ORG': '#D3D3D3',
 'PER': '#D3D3D3'
}
opcoes = {'ents': rotulos, 'colors': cores}
spacy.displacy.render(doc, style = 'ent', jupyter = True, options = opcoes)